package com.xiaosong.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("v_access_config", "id", VAccessConfig.class);
		arp.addMapping("v_app_checkindate", "id", VAppCheckindate.class);
		arp.addMapping("v_app_checkintime", "id", VAppCheckintime.class);
		arp.addMapping("v_app_menu", "id", VAppMenu.class);
		arp.addMapping("v_app_user", "id", VAppUser.class);
		arp.addMapping("v_app_user_account", "id", VAppUserAccount.class);
		arp.addMapping("v_app_user_message", "id", VAppUserMessage.class);
		arp.addMapping("v_app_visitor_record", "id", VAppVisitorRecord.class);
		arp.addMapping("v_app_yaoyue_record", "id", VAppYaoyueRecord.class);
		arp.addMapping("v_business", "id", VBusiness.class);
		arp.addMapping("v_comp_vip_user", "id", VCompVipUser.class);
		arp.addMapping("v_company", "id", VCompany.class);
		arp.addMapping("v_d_user", "id", VDUser.class);
		arp.addMapping("v_d_visitor_inout", "id", VDVisitorInout.class);
		arp.addMapping("v_dept", "id", VDept.class);
		arp.addMapping("v_dept_user", "id", VDeptUser.class);
		arp.addMapping("v_device", "id", VDevice.class);
		arp.addMapping("v_dictionaries", "id", VDictionaries.class);
		arp.addMapping("v_key", "id", VKey.class);
		arp.addMapping("v_kq_attendrule", "id", VKqAttendrule.class);
		arp.addMapping("v_params", "id", VParams.class);
	}
}

