package com.xiaosong.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("ACT_EVT_LOG", "LOG_NR_", ActEvtLog.class);
		arp.addMapping("ACT_GE_BYTEARRAY", "ID_", ActGeBytearray.class);
		arp.addMapping("ACT_GE_PROPERTY", "NAME_", ActGeProperty.class);
		arp.addMapping("ACT_HI_ACTINST", "ID_", ActHiActinst.class);
		arp.addMapping("ACT_HI_ATTACHMENT", "ID_", ActHiAttachment.class);
		arp.addMapping("ACT_HI_COMMENT", "ID_", ActHiComment.class);
		arp.addMapping("ACT_HI_DETAIL", "ID_", ActHiDetail.class);
		arp.addMapping("ACT_HI_IDENTITYLINK", "ID_", ActHiIdentitylink.class);
		arp.addMapping("ACT_HI_PROCINST", "ID_", ActHiProcinst.class);
		arp.addMapping("ACT_HI_TASKINST", "ID_", ActHiTaskinst.class);
		arp.addMapping("ACT_HI_VARINST", "ID_", ActHiVarinst.class);
		arp.addMapping("ACT_ID_GROUP", "ID_", ActIdGroup.class);
		arp.addMapping("ACT_ID_INFO", "ID_", ActIdInfo.class);
		// Composite Primary Key order: GROUP_ID_,USER_ID_
		arp.addMapping("ACT_ID_MEMBERSHIP", "GROUP_ID_,USER_ID_", ActIdMembership.class);
		arp.addMapping("ACT_ID_USER", "ID_", ActIdUser.class);
		arp.addMapping("ACT_RE_DEPLOYMENT", "ID_", ActReDeployment.class);
		arp.addMapping("ACT_RE_MODEL", "ID_", ActReModel.class);
		arp.addMapping("ACT_RE_PROCDEF", "ID_", ActReProcdef.class);
		arp.addMapping("ACT_RU_EVENT_SUBSCR", "ID_", ActRuEventSubscr.class);
		arp.addMapping("ACT_RU_EXECUTION", "ID_", ActRuExecution.class);
		arp.addMapping("ACT_RU_IDENTITYLINK", "ID_", ActRuIdentitylink.class);
		arp.addMapping("ACT_RU_JOB", "ID_", ActRuJob.class);
		arp.addMapping("ACT_RU_TASK", "ID_", ActRuTask.class);
		arp.addMapping("ACT_RU_VARIABLE", "ID_", ActRuVariable.class);
		arp.addMapping("v_ad_banner", "id", VAdBanner.class);
		arp.addMapping("v_app_checkindate", "id", VAppCheckindate.class);
		arp.addMapping("v_app_checkintime", "id", VAppCheckintime.class);
		arp.addMapping("v_app_menu", "id", VAppMenu.class);
		arp.addMapping("v_app_role", "id", VAppRole.class);
		arp.addMapping("v_app_role_menu", "id", VAppRoleMenu.class);
		arp.addMapping("v_app_user_message", "id", VAppUserMessage.class);
		arp.addMapping("v_app_user_notice", "id", VAppUserNotice.class);
		arp.addMapping("v_app_version", "id", VAppVersion.class);
		arp.addMapping("v_black_user", "id", VBlackUser.class);
		arp.addMapping("v_business", "id", VBusiness.class);
		arp.addMapping("v_car", "id", VCar.class);
		arp.addMapping("v_comp_vip_user", "id", VCompVipUser.class);
		arp.addMapping("v_d_inout", "id", VDInout.class);
		arp.addMapping("v_dept", "id", VDept.class);
		arp.addMapping("v_dept_user", "id", VDeptUser.class);
		arp.addMapping("v_device", "id", VDevice.class);
		arp.addMapping("v_dictionaries", "id", VDictionaries.class);
		arp.addMapping("v_error_log", "id", VErrorLog.class);
		arp.addMapping("v_key", "id", VKey.class);
		arp.addMapping("v_kq_attendrule", "id", VKqAttendrule.class);
		arp.addMapping("v_local_auth", "id", VLocalAuth.class);
		arp.addMapping("v_machine", "id", VMachine.class);
		arp.addMapping("v_news", "id", VNews.class);
		arp.addMapping("v_notice", "id", VNotice.class);
		arp.addMapping("v_org", "id", VOrg.class);
		arp.addMapping("v_out_visitor", "id", VOutVisitor.class);
		arp.addMapping("v_params", "id", VParams.class);
		arp.addMapping("v_post", "id", VPost.class);
		arp.addMapping("v_sync", "id", VSync.class);
		arp.addMapping("v_sys_config", "id", VSysConfig.class);
		arp.addMapping("v_sys_user", "id", VSysUser.class);
		arp.addMapping("v_temp", "id", VTemp.class);
		arp.addMapping("v_user_auth", "id", VUserAuth.class);
		arp.addMapping("v_user_friend", "id", VUserFriend.class);
		arp.addMapping("v_user_key", "id", VUserKey.class);
		arp.addMapping("v_user_post", "id", VUserPost.class);
		arp.addMapping("v_user_role", "id", VUserRole.class);
		arp.addMapping("v_user_role_auth", "id", VUserRoleAuth.class);
		arp.addMapping("v_visitor_record", "id", VVisitorRecord.class);
		arp.addMapping("wk_record", "id", WkRecord.class);
	}
}

