package com.xiaosong.model;

import com.xiaosong.model.base.BaseActEvtLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ActEvtLog extends BaseActEvtLog<ActEvtLog> {
	public static final ActEvtLog dao = new ActEvtLog().dao();
}
