package com.xiaosong.model;

import com.xiaosong.model.base.BaseActGeBytearray;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ActGeBytearray extends BaseActGeBytearray<ActGeBytearray> {
	public static final ActGeBytearray dao = new ActGeBytearray().dao();
}
