package com.xiaosong.model;

import com.xiaosong.model.base.BaseActGeProperty;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ActGeProperty extends BaseActGeProperty<ActGeProperty> {
	public static final ActGeProperty dao = new ActGeProperty().dao();
}
