package com.xiaosong.model;

import com.xiaosong.model.base.BaseActHiDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ActHiDetail extends BaseActHiDetail<ActHiDetail> {
	public static final ActHiDetail dao = new ActHiDetail().dao();
}
