package com.xiaosong.model;

import com.xiaosong.model.base.BaseActHiProcinst;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ActHiProcinst extends BaseActHiProcinst<ActHiProcinst> {
	public static final ActHiProcinst dao = new ActHiProcinst().dao();
}
