package com.xiaosong.model;

import com.xiaosong.model.base.BaseActHiActinst;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ActHiActinst extends BaseActHiActinst<ActHiActinst> {
	public static final ActHiActinst dao = new ActHiActinst().dao();
}
