package com.xiaosong.model;

import com.xiaosong.model.base.BaseActHiTaskinst;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ActHiTaskinst extends BaseActHiTaskinst<ActHiTaskinst> {
	public static final ActHiTaskinst dao = new ActHiTaskinst().dao();
}
