package com.xiaosong.model;

import com.xiaosong.model.base.BaseActHiVarinst;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ActHiVarinst extends BaseActHiVarinst<ActHiVarinst> {
	public static final ActHiVarinst dao = new ActHiVarinst().dao();
}
