package com.xiaosong.model;

import com.xiaosong.model.base.BaseActHiComment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ActHiComment extends BaseActHiComment<ActHiComment> {
	public static final ActHiComment dao = new ActHiComment().dao();
}
