package com.xiaosong.model;

import com.xiaosong.model.base.BaseActHiIdentitylink;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ActHiIdentitylink extends BaseActHiIdentitylink<ActHiIdentitylink> {
	public static final ActHiIdentitylink dao = new ActHiIdentitylink().dao();
}
