package com.xiaosong.model;

import com.xiaosong.model.base.BaseActHiAttachment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ActHiAttachment extends BaseActHiAttachment<ActHiAttachment> {
	public static final ActHiAttachment dao = new ActHiAttachment().dao();
}
