package com.xiaosong.model;

import com.xiaosong.model.base.BaseActIdMembership;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ActIdMembership extends BaseActIdMembership<ActIdMembership> {
	public static final ActIdMembership dao = new ActIdMembership().dao();
}
