package com.xiaosong.model;

import com.xiaosong.model.base.BaseActIdUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ActIdUser extends BaseActIdUser<ActIdUser> {
	public static final ActIdUser dao = new ActIdUser().dao();
}
