package com.xiaosong.model;

import com.xiaosong.model.base.BaseActIdGroup;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ActIdGroup extends BaseActIdGroup<ActIdGroup> {
	public static final ActIdGroup dao = new ActIdGroup().dao();
}
