package com.xiaosong.model;

import com.xiaosong.model.base.BaseActIdInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ActIdInfo extends BaseActIdInfo<ActIdInfo> {
	public static final ActIdInfo dao = new ActIdInfo().dao();
}
