package com.xiaosong.model;

import com.xiaosong.model.base.BaseActReProcdef;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ActReProcdef extends BaseActReProcdef<ActReProcdef> {
	public static final ActReProcdef dao = new ActReProcdef().dao();
}
