package com.xiaosong.model;

import com.xiaosong.model.base.BaseActReDeployment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ActReDeployment extends BaseActReDeployment<ActReDeployment> {
	public static final ActReDeployment dao = new ActReDeployment().dao();
}
