package com.xiaosong.model;

import com.xiaosong.model.base.BaseActRuJob;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ActRuJob extends BaseActRuJob<ActRuJob> {
	public static final ActRuJob dao = new ActRuJob().dao();
}
