package com.xiaosong.model;

import com.xiaosong.model.base.BaseActRuTask;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ActRuTask extends BaseActRuTask<ActRuTask> {
	public static final ActRuTask dao = new ActRuTask().dao();
}
