package com.xiaosong.model;

import com.xiaosong.model.base.BaseActRuVariable;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ActRuVariable extends BaseActRuVariable<ActRuVariable> {
	public static final ActRuVariable dao = new ActRuVariable().dao();
}
