package com.xiaosong.model;

import com.xiaosong.model.base.BaseActRuIdentitylink;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ActRuIdentitylink extends BaseActRuIdentitylink<ActRuIdentitylink> {
	public static final ActRuIdentitylink dao = new ActRuIdentitylink().dao();
}
