package com.xiaosong.model;

import com.xiaosong.model.base.BaseActRuEventSubscr;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ActRuEventSubscr extends BaseActRuEventSubscr<ActRuEventSubscr> {
	public static final ActRuEventSubscr dao = new ActRuEventSubscr().dao();
}
