package com.xiaosong.model;

import com.xiaosong.model.base.BaseActRuExecution;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ActRuExecution extends BaseActRuExecution<ActRuExecution> {
	public static final ActRuExecution dao = new ActRuExecution().dao();
}
