package com.xiaosong.model;

import com.xiaosong.model.base.BaseTblAccess;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TblAccess extends BaseTblAccess<TblAccess> {
	public static final TblAccess dao = new TblAccess().dao();
}
