package com.xiaosong.model;

import com.xiaosong.model.base.BaseTblAccessOrg;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TblAccessOrg extends BaseTblAccessOrg<TblAccessOrg> {
	public static final TblAccessOrg dao = new TblAccessOrg().dao();
}
