package com.xiaosong.model;

import com.xiaosong.model.base.BaseTblAccessDept;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TblAccessDept extends BaseTblAccessDept<TblAccessDept> {
	public static final TblAccessDept dao = new TblAccessDept().dao();
}
