package com.xiaosong.model;

import com.xiaosong.model.base.BaseTblSms;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TblSms extends BaseTblSms<TblSms> {
	public static final TblSms dao = new TblSms().dao();
}
