package com.xiaosong.model;

import com.xiaosong.model.base.BaseTblSmsTemplate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TblSmsTemplate extends BaseTblSmsTemplate<TblSmsTemplate> {
	public static final TblSmsTemplate dao = new TblSmsTemplate().dao();
}
