package com.xiaosong.model;

import com.xiaosong.model.base.BaseVAccessConfig;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VAccessConfig extends BaseVAccessConfig<VAccessConfig> {
	public static final VAccessConfig dao = new VAccessConfig().dao();
}
