package com.xiaosong.model;

import com.xiaosong.model.base.BaseVAdBanner;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VAdBanner extends BaseVAdBanner<VAdBanner> {
	public static final VAdBanner dao = new VAdBanner().dao();
}
