package com.xiaosong.model;

import com.xiaosong.model.base.BaseVAppVisitorRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VAppVisitorRecord extends BaseVAppVisitorRecord<VAppVisitorRecord> {
	public static final VAppVisitorRecord dao = new VAppVisitorRecord().dao();
}
