package com.xiaosong.model;

import com.xiaosong.model.base.BaseVAppVersion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VAppVersion extends BaseVAppVersion<VAppVersion> {
	public static final VAppVersion dao = new VAppVersion().dao();
}
