package com.xiaosong.model;

import com.xiaosong.model.base.BaseVAppUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VAppUser extends BaseVAppUser<VAppUser> {
	public static final VAppUser dao = new VAppUser().dao();
}
