package com.xiaosong.model;

import com.xiaosong.model.base.BaseVAppMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VAppMenu extends BaseVAppMenu<VAppMenu> {
	public static final VAppMenu dao = new VAppMenu().dao();
}
