package com.xiaosong.model;

import com.xiaosong.model.base.BaseVAppUserMessage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VAppUserMessage extends BaseVAppUserMessage<VAppUserMessage> {
	public static final VAppUserMessage dao = new VAppUserMessage().dao();
}
