package com.xiaosong.model;

import com.xiaosong.model.base.BaseVAppRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VAppRole extends BaseVAppRole<VAppRole> {
	public static final VAppRole dao = new VAppRole().dao();
}
