package com.xiaosong.model;

import com.xiaosong.model.base.BaseVAppUserNotice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VAppUserNotice extends BaseVAppUserNotice<VAppUserNotice> {
	public static final VAppUserNotice dao = new VAppUserNotice().dao();
}
