package com.xiaosong.model;

import com.xiaosong.model.base.BaseVAppYaoyueRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VAppYaoyueRecord extends BaseVAppYaoyueRecord<VAppYaoyueRecord> {
	public static final VAppYaoyueRecord dao = new VAppYaoyueRecord().dao();
}
