package com.xiaosong.model;

import com.xiaosong.model.base.BaseVAppCheckindate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VAppCheckindate extends BaseVAppCheckindate<VAppCheckindate> {
	public static final VAppCheckindate dao = new VAppCheckindate().dao();
}
