package com.xiaosong.model;

import com.xiaosong.model.base.BaseVAppCheckintime;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VAppCheckintime extends BaseVAppCheckintime<VAppCheckintime> {
	public static final VAppCheckintime dao = new VAppCheckintime().dao();
}
