package com.xiaosong.model;

import com.xiaosong.model.base.BaseVAppUserAccount;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VAppUserAccount extends BaseVAppUserAccount<VAppUserAccount> {
	public static final VAppUserAccount dao = new VAppUserAccount().dao();
}
