package com.xiaosong.model;

import com.xiaosong.model.base.BaseVAppNotice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VAppNotice extends BaseVAppNotice<VAppNotice> {
	public static final VAppNotice dao = new VAppNotice().dao();
}
