package com.xiaosong.model;

import com.xiaosong.model.base.BaseVAppRoleMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VAppRoleMenu extends BaseVAppRoleMenu<VAppRoleMenu> {
	public static final VAppRoleMenu dao = new VAppRoleMenu().dao();
}
