package com.xiaosong.model;

import com.xiaosong.model.base.BaseVBlackUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VBlackUser extends BaseVBlackUser<VBlackUser> {
	public static final VBlackUser dao = new VBlackUser().dao();
}
