package com.xiaosong.model;

import com.xiaosong.model.base.BaseVBusiness;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VBusiness extends BaseVBusiness<VBusiness> {
	public static final VBusiness dao = new VBusiness().dao();
}
