package com.xiaosong.model;

import com.xiaosong.model.base.BaseVCar;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VCar extends BaseVCar<VCar> {
	public static final VCar dao = new VCar().dao();
}
