package com.xiaosong.model;

import com.xiaosong.model.base.BaseVCompVipUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VCompVipUser extends BaseVCompVipUser<VCompVipUser> {
	public static final VCompVipUser dao = new VCompVipUser().dao();
}
