package com.xiaosong.model;

import com.xiaosong.model.base.BaseVCompany;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VCompany extends BaseVCompany<VCompany> {
	public static final VCompany dao = new VCompany().dao();
}
