package com.xiaosong.model;

import com.xiaosong.model.base.BaseVDeptUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VDeptUser extends BaseVDeptUser<VDeptUser> {
	public static final VDeptUser dao = new VDeptUser().dao();
}
