package com.xiaosong.model;

import com.xiaosong.model.base.BaseVDeptCopy;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VDeptCopy extends BaseVDeptCopy<VDeptCopy> {
	public static final VDeptCopy dao = new VDeptCopy().dao();
}
