package com.xiaosong.model;

import com.xiaosong.model.base.BaseVDept;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VDept extends BaseVDept<VDept> {
	public static final VDept dao = new VDept().dao();
}
