package com.xiaosong.model;

import com.xiaosong.model.base.BaseVDeviceWincc;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VDeviceWincc extends BaseVDeviceWincc<VDeviceWincc> {
	public static final VDeviceWincc dao = new VDeviceWincc().dao();
}
