package com.xiaosong.model;

import com.xiaosong.model.base.BaseVDevice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VDevice extends BaseVDevice<VDevice> {
	public static final VDevice dao = new VDevice().dao();
}
