package com.xiaosong.model;

import com.xiaosong.model.base.BaseVDictionaries;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VDictionaries extends BaseVDictionaries<VDictionaries> {
	public static final VDictionaries dao = new VDictionaries().dao();
}
