package com.xiaosong.model;

import com.xiaosong.model.base.BaseVDInout;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VDInout extends BaseVDInout<VDInout> {
	public static final VDInout dao = new VDInout().dao();
}
