package com.xiaosong.model;

import com.xiaosong.model.base.BaseVDUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VDUser extends BaseVDUser<VDUser> {
	public static final VDUser dao = new VDUser().dao();
}
