package com.xiaosong.model;

import com.xiaosong.model.base.BaseVDVisitorInout;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VDVisitorInout extends BaseVDVisitorInout<VDVisitorInout> {
	public static final VDVisitorInout dao = new VDVisitorInout().dao();
}
