package com.xiaosong.model;

import com.xiaosong.model.base.BaseVErrorLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VErrorLog extends BaseVErrorLog<VErrorLog> {
	public static final VErrorLog dao = new VErrorLog().dao();
}
