package com.xiaosong.model;

import com.xiaosong.model.base.BaseVKey;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VKey extends BaseVKey<VKey> {
	public static final VKey dao = new VKey().dao();
}
