package com.xiaosong.model;

import com.xiaosong.model.base.BaseVKqAttendrule;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VKqAttendrule extends BaseVKqAttendrule<VKqAttendrule> {
	public static final VKqAttendrule dao = new VKqAttendrule().dao();
}
