package com.xiaosong.model;

import com.xiaosong.model.base.BaseVLocalAuth;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VLocalAuth extends BaseVLocalAuth<VLocalAuth> {
	public static final VLocalAuth dao = new VLocalAuth().dao();
}
