package com.xiaosong.model;

import com.xiaosong.model.base.BaseVMachine;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VMachine extends BaseVMachine<VMachine> {
	public static final VMachine dao = new VMachine().dao();
}
