package com.xiaosong.model;

import com.xiaosong.model.base.BaseVNews;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VNews extends BaseVNews<VNews> {
	public static final VNews dao = new VNews().dao();
}
