package com.xiaosong.model;

import com.xiaosong.model.base.BaseVNotice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VNotice extends BaseVNotice<VNotice> {
	public static final VNotice dao = new VNotice().dao();
}
