package com.xiaosong.model;

import com.xiaosong.model.base.BaseVOrg;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VOrg extends BaseVOrg<VOrg> {
	public static final VOrg dao = new VOrg().dao();
}
