package com.xiaosong.model;

import com.xiaosong.model.base.BaseVOutVisitor;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VOutVisitor extends BaseVOutVisitor<VOutVisitor> {
	public static final VOutVisitor dao = new VOutVisitor().dao();
}
