package com.xiaosong.model;

import com.xiaosong.model.base.BaseVParams;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VParams extends BaseVParams<VParams> {
	public static final VParams dao = new VParams().dao();
}
