package com.xiaosong.model;

import com.xiaosong.model.base.BaseVPost;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VPost extends BaseVPost<VPost> {
	public static final VPost dao = new VPost().dao();
}
