package com.xiaosong.model;

import com.xiaosong.model.base.BaseVPosp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VPosp extends BaseVPosp<VPosp> {
	public static final VPosp dao = new VPosp().dao();
}
