package com.xiaosong.model;

import com.xiaosong.model.base.BaseVSync;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VSync extends BaseVSync<VSync> {
	public static final VSync dao = new VSync().dao();
}
