package com.xiaosong.model;

import com.xiaosong.model.base.BaseVSysUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VSysUser extends BaseVSysUser<VSysUser> {
	public static final VSysUser dao = new VSysUser().dao();
}
