package com.xiaosong.model;

import com.xiaosong.model.base.BaseVSysConfig;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VSysConfig extends BaseVSysConfig<VSysConfig> {
	public static final VSysConfig dao = new VSysConfig().dao();
}
