package com.xiaosong.model;

import com.xiaosong.model.base.BaseVTemp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VTemp extends BaseVTemp<VTemp> {
	public static final VTemp dao = new VTemp().dao();
}
