package com.xiaosong.model;

import com.xiaosong.model.base.BaseVUserPost;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VUserPost extends BaseVUserPost<VUserPost> {
	public static final VUserPost dao = new VUserPost().dao();
}
