package com.xiaosong.model;

import com.xiaosong.model.base.BaseVUserRoleAuth;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VUserRoleAuth extends BaseVUserRoleAuth<VUserRoleAuth> {
	public static final VUserRoleAuth dao = new VUserRoleAuth().dao();
}
