package com.xiaosong.model;

import com.xiaosong.model.base.BaseVUserAuth;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VUserAuth extends BaseVUserAuth<VUserAuth> {
	public static final VUserAuth dao = new VUserAuth().dao();
}
