package com.xiaosong.model;

import com.xiaosong.model.base.BaseVUserFriend;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VUserFriend extends BaseVUserFriend<VUserFriend> {
	public static final VUserFriend dao = new VUserFriend().dao();
}
