package com.xiaosong.model;

import com.xiaosong.model.base.BaseVUserRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VUserRole extends BaseVUserRole<VUserRole> {
	public static final VUserRole dao = new VUserRole().dao();
}
