package com.xiaosong.model;

import com.xiaosong.model.base.BaseVUserKey;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VUserKey extends BaseVUserKey<VUserKey> {
	public static final VUserKey dao = new VUserKey().dao();
}
