package com.xiaosong.model;

import com.xiaosong.model.base.BaseVVisitorRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VVisitorRecord extends BaseVVisitorRecord<VVisitorRecord> {
	public static final VVisitorRecord dao = new VVisitorRecord().dao();
}
