package com.xiaosong.model;

import com.xiaosong.model.base.BaseWkRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WkRecord extends BaseWkRecord<WkRecord> {
	public static final WkRecord dao = new WkRecord().dao();
}
