package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseVAppYaoyueRecord<M extends BaseVAppYaoyueRecord<M>> extends Model<M> implements IBean {

	/**
	 * 主键ID
	 */
	public M setId(Long id) {
		set("id", id);
		return (M)this;
	}

	/**
	 * 主键ID
	 */
	public Long getId() {
		return getLong("id");
	}

	/**
	 * 开始时间
	 */
	public M setVisitDate(String visitDate) {
		set("visitDate", visitDate);
		return (M)this;
	}

	/**
	 * 开始时间
	 */
	public String getVisitDate() {
		return getStr("visitDate");
	}

	/**
	 * 当前登录人登录账号
	 */
	public M setUserId(String userId) {
		set("userId", userId);
		return (M)this;
	}

	/**
	 * 当前登录人登录账号
	 */
	public String getUserId() {
		return getStr("userId");
	}

	/**
	 * 备注
	 */
	public M setReason(String reason) {
		set("reason", reason);
		return (M)this;
	}

	/**
	 * 备注
	 */
	public String getReason() {
		return getStr("reason");
	}

	/**
	 * '状态 applying:申请中，applySuccess:接受访问，applyFail:拒绝访问',
	 */
	public M setCstatus(String cstatus) {
		set("cstatus", cstatus);
		return (M)this;
	}

	/**
	 * '状态 applying:申请中，applySuccess:接受访问，applyFail:拒绝访问',
	 */
	public String getCstatus() {
		return getStr("cstatus");
	}

	/**
	 * 操作人的当前时间
	 */
	public M setEndDate(String endDate) {
		set("endDate", endDate);
		return (M)this;
	}

	/**
	 * 操作人的当前时间
	 */
	public String getEndDate() {
		return getStr("endDate");
	}

	/**
	 * 结束时间
	 */
	public M setAnswerContent(String answerContent) {
		set("answerContent", answerContent);
		return (M)this;
	}

	/**
	 * 结束时间
	 */
	public String getAnswerContent() {
		return getStr("answerContent");
	}

	/**
	 * 手机号
	 */
	public M setOrgCode(String orgCode) {
		set("orgCode", orgCode);
		return (M)this;
	}

	/**
	 * 手机号
	 */
	public String getOrgCode() {
		return getStr("orgCode");
	}

	/**
	 * 当前登录人companyId
	 */
	public M setCompanyId(Long companyId) {
		set("companyId", companyId);
		return (M)this;
	}

	/**
	 * 当前登录人companyId
	 */
	public Long getCompanyId() {
		return getLong("companyId");
	}

	/**
	 * 名称
	 */
	public M setYaoyuetitle(String yaoyuetitle) {
		set("yaoyuetitle", yaoyuetitle);
		return (M)this;
	}

	/**
	 * 名称
	 */
	public String getYaoyuetitle() {
		return getStr("yaoyuetitle");
	}

	/**
	 * 邀请人姓名
	 */
	public M setAddusername(String addusername) {
		set("addusername", addusername);
		return (M)this;
	}

	/**
	 * 邀请人姓名
	 */
	public String getAddusername() {
		return getStr("addusername");
	}

	/**
	 * 扩展字段1
	 */
	public M setExp1(String exp1) {
		set("exp1", exp1);
		return (M)this;
	}

	/**
	 * 扩展字段1
	 */
	public String getExp1() {
		return getStr("exp1");
	}

	/**
	 * 扩展字段2
	 */
	public M setExp2(String exp2) {
		set("exp2", exp2);
		return (M)this;
	}

	/**
	 * 扩展字段2
	 */
	public String getExp2() {
		return getStr("exp2");
	}

}
