package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseVPost<M extends BaseVPost<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setPostName(java.lang.String postName) {
		set("postName", postName);
		return (M)this;
	}
	
	public java.lang.String getPostName() {
		return getStr("postName");
	}

	public M setPostAuth(java.lang.String postAuth) {
		set("postAuth", postAuth);
		return (M)this;
	}
	
	public java.lang.String getPostAuth() {
		return getStr("postAuth");
	}

	public M setPost(java.lang.String post) {
		set("post", post);
		return (M)this;
	}
	
	public java.lang.String getPost() {
		return getStr("post");
	}

}
