package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseVAppVisitorRecord<M extends BaseVAppVisitorRecord<M>> extends Model<M> implements IBean {

	/**
	 * 智慧访客
	 */
	public M setId(Long id) {
		set("id", id);
		return (M)this;
	}

	/**
	 * 智慧访客
	 */
	public Long getId() {
		return getLong("id");
	}

	/**
	 * 访问日期
	 */
	public M setVisitDate(String visitDate) {
		set("visitDate", visitDate);
		return (M)this;
	}

	/**
	 * 访问日期
	 */
	public String getVisitDate() {
		return getStr("visitDate");
	}

	/**
	 * 访问时间
	 */
	public M setVisitTime(String visitTime) {
		set("visitTime", visitTime);
		return (M)this;
	}

	/**
	 * 访问时间
	 */
	public String getVisitTime() {
		return getStr("visitTime");
	}

	/**
	 * 访客id
	 */
	public M setUserId(Long userId) {
		set("userId", userId);
		return (M)this;
	}

	/**
	 * 访客id
	 */
	public Long getUserId() {
		return getLong("userId");
	}

	/**
	 * 被访者id
	 */
	public M setVisitorId(Long visitorId) {
		set("visitorId", visitorId);
		return (M)this;
	}

	/**
	 * 被访者id
	 */
	public Long getVisitorId() {
		return getLong("visitorId");
	}

	/**
	 * 访问原因
	 */
	public M setReason(String reason) {
		set("reason", reason);
		return (M)this;
	}

	/**
	 * 访问原因
	 */
	public String getReason() {
		return getStr("reason");
	}

	/**
	 * 状态 applying:申请中，applySuccess:接受访问，applyFail:拒绝访问
	 */
	public M setCstatus(String cstatus) {
		set("cstatus", cstatus);
		return (M)this;
	}

	/**
	 * 状态 applying:申请中，applySuccess:接受访问，applyFail:拒绝访问
	 */
	public String getCstatus() {
		return getStr("cstatus");
	}

	/**
	 * 日期类型:无期：Indefinite,有限期:limitPeriod
	 */
	public M setDateType(String dateType) {
		set("dateType", dateType);
		return (M)this;
	}

	/**
	 * 日期类型:无期：Indefinite,有限期:limitPeriod
	 */
	public String getDateType() {
		return getStr("dateType");
	}

	/**
	 * 开始日期
	 */
	public M setStartDate(String startDate) {
		set("startDate", startDate);
		return (M)this;
	}

	/**
	 * 开始日期
	 */
	public String getStartDate() {
		return getStr("startDate");
	}

	/**
	 * 结束日期
	 */
	public M setEndDate(String endDate) {
		set("endDate", endDate);
		return (M)this;
	}

	/**
	 * 结束日期
	 */
	public String getEndDate() {
		return getStr("endDate");
	}

	/**
	 * 被访者回复
	 */
	public M setAnswerContent(String answerContent) {
		set("answerContent", answerContent);
		return (M)this;
	}

	/**
	 * 被访者回复
	 */
	public String getAnswerContent() {
		return getStr("answerContent");
	}

	/**
	 * 被访者大楼编码
	 */
	public M setOrgCode(String orgCode) {
		set("orgCode", orgCode);
		return (M)this;
	}

	/**
	 * 被访者大楼编码
	 */
	public String getOrgCode() {
		return getStr("orgCode");
	}

	/**
	 * 被访者公司Id
	 */
	public M setCompanyId(Long companyId) {
		set("companyId", companyId);
		return (M)this;
	}

	/**
	 * 被访者公司Id
	 */
	public Long getCompanyId() {
		return getLong("companyId");
	}

	/**
	 * 访问类型b浏览器
	 */
	public M setVitype(String vitype) {
		set("vitype", vitype);
		return (M)this;
	}

	/**
	 * 访问类型b浏览器
	 */
	public String getVitype() {
		return getStr("vitype");
	}

	/**
	 * 1--访问，2--邀约
	 */
	public M setRecordType(Integer recordType) {
		set("recordType", recordType);
		return (M)this;
	}

	/**
	 * 1--访问，2--邀约
	 */
	public Integer getRecordType() {
		return getInt("recordType");
	}

	/**
	 * 审核日期
	 */
	public M setReplyDate(String replyDate) {
		set("replyDate", replyDate);
		return (M)this;
	}

	/**
	 * 审核日期
	 */
	public String getReplyDate() {
		return getStr("replyDate");
	}

	/**
	 * 审核时间
	 */
	public M setReplyTime(String replyTime) {
		set("replyTime", replyTime);
		return (M)this;
	}

	/**
	 * 审核时间
	 */
	public String getReplyTime() {
		return getStr("replyTime");
	}

	/**
	 * 审核人ID
	 */
	public M setReplyUserId(Long replyUserId) {
		set("replyUserId", replyUserId);
		return (M)this;
	}

	/**
	 * 审核人ID
	 */
	public Long getReplyUserId() {
		return getLong("replyUserId");
	}

	/**
	 * 是否已下发用户 T--是 F--否
	 */
	public M setIsReceive(String isReceive) {
		set("isReceive", isReceive);
		return (M)this;
	}

	/**
	 * 是否已下发用户 T--是 F--否
	 */
	public String getIsReceive() {
		return getStr("isReceive");
	}

	/**
	 * 扩展字段1
	 */
	public M setExp1(String exp1) {
		set("exp1", exp1);
		return (M)this;
	}

	/**
	 * 扩展字段1
	 */
	public String getExp1() {
		return getStr("exp1");
	}

	/**
	 * 扩展字段2
	 */
	public M setExp2(String exp2) {
		set("exp2", exp2);
		return (M)this;
	}

	/**
	 * 扩展字段2
	 */
	public String getExp2() {
		return getStr("exp2");
	}

}
