package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseVCompVipUser<M extends BaseVCompVipUser<M>> extends Model<M> implements IBean {

	/**
	 * VIP管理
	 */
	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * VIP管理
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 大楼id
	 */
	public M setOrgId(java.lang.Long orgId) {
		set("orgId", orgId);
		return (M)this;
	}
	
	/**
	 * 大楼id
	 */
	public java.lang.Long getOrgId() {
		return getLong("orgId");
	}

	/**
	 * 更新时间HH:mm:ss hh"ii:ss
	 */
	public M setUpdateTime(java.lang.String updateTime) {
		set("updateTime", updateTime);
		return (M)this;
	}
	
	/**
	 * 更新时间HH:mm:ss hh"ii:ss
	 */
	public java.lang.String getUpdateTime() {
		return getStr("updateTime");
	}

	/**
	 * 用户Id
	 */
	public M setUserId(java.lang.Long userId) {
		set("userId", userId);
		return (M)this;
	}
	
	/**
	 * 用户Id
	 */
	public java.lang.Long getUserId() {
		return getLong("userId");
	}

	/**
	 * 请求id
	 */
	public M setPostId(java.lang.Long postId) {
		set("postId", postId);
		return (M)this;
	}
	
	/**
	 * 请求id
	 */
	public java.lang.Long getPostId() {
		return getLong("postId");
	}

	/**
	 * 用户姓名
	 */
	public M setUserName(java.lang.String userName) {
		set("userName", userName);
		return (M)this;
	}
	
	/**
	 * 用户姓名
	 */
	public java.lang.String getUserName() {
		return getStr("userName");
	}

	/**
	 * 创建日期yy:MM:dd
	 */
	public M setCreateDate(java.lang.String createDate) {
		set("createDate", createDate);
		return (M)this;
	}
	
	/**
	 * 创建日期yy:MM:dd
	 */
	public java.lang.String getCreateDate() {
		return getStr("createDate");
	}

	/**
	 * 创建时间HH:mm:ss
	 */
	public M setCreateTime(java.lang.String createTime) {
		set("createTime", createTime);
		return (M)this;
	}
	
	/**
	 * 创建时间HH:mm:ss
	 */
	public java.lang.String getCreateTime() {
		return getStr("createTime");
	}

	/**
	 * 角色:(staff:普通员工,manage:管理员,front:前台)
	 */
	public M setRoleType(java.lang.String roleType) {
		set("roleType", roleType);
		return (M)this;
	}
	
	/**
	 * 角色:(staff:普通员工,manage:管理员,front:前台)
	 */
	public java.lang.String getRoleType() {
		return getStr("roleType");
	}

	/**
	 * 状态：确认:applySuc/未确认:applying/确认不通过:applyFail
	 */
	public M setStatus(java.lang.String status) {
		set("status", status);
		return (M)this;
	}
	
	/**
	 * 状态：确认:applySuc/未确认:applying/确认不通过:applyFail
	 */
	public java.lang.String getStatus() {
		return getStr("status");
	}

	/**
	 * normal为正常，deleted为删除
	 */
	public M setCurrentStatus(java.lang.String currentStatus) {
		set("currentStatus", currentStatus);
		return (M)this;
	}
	
	/**
	 * normal为正常，deleted为删除
	 */
	public java.lang.String getCurrentStatus() {
		return getStr("currentStatus");
	}

}
