package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseVOrg<M extends BaseVOrg<M>> extends Model<M> implements IBean {

	/**
	 * 大楼
	 */
	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 大楼
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 大楼编码
	 */
	public M setOrgCode(java.lang.String orgCode) {
		set("org_code", orgCode);
		return (M)this;
	}
	
	/**
	 * 大楼编码
	 */
	public java.lang.String getOrgCode() {
		return getStr("org_code");
	}

	/**
	 * 大楼名
	 */
	public M setOrgName(java.lang.String orgName) {
		set("org_name", orgName);
		return (M)this;
	}
	
	/**
	 * 大楼名
	 */
	public java.lang.String getOrgName() {
		return getStr("org_name");
	}

	/**
	 * 关系
	 */
	public M setSid(java.lang.Long sid) {
		set("sid", sid);
		return (M)this;
	}
	
	/**
	 * 关系
	 */
	public java.lang.Long getSid() {
		return getLong("sid");
	}

	/**
	 * 置顶
	 */
	public M setIstop(java.lang.String istop) {
		set("istop", istop);
		return (M)this;
	}
	
	/**
	 * 置顶
	 */
	public java.lang.String getIstop() {
		return getStr("istop");
	}

	/**
	 * 大楼图标
	 */
	public M setOrgIcon(java.lang.String orgIcon) {
		set("org_icon", orgIcon);
		return (M)this;
	}
	
	/**
	 * 大楼图标
	 */
	public java.lang.String getOrgIcon() {
		return getStr("org_icon");
	}

	/**
	 * 关系
	 */
	public M setRelationNo(java.lang.String relationNo) {
		set("relation_no", relationNo);
		return (M)this;
	}
	
	/**
	 * 关系
	 */
	public java.lang.String getRelationNo() {
		return getStr("relation_no");
	}

	/**
	 * 0:正常；1:禁止
	 */
	public M setSstatus(java.lang.String sstatus) {
		set("sstatus", sstatus);
		return (M)this;
	}
	
	/**
	 * 0:正常；1:禁止
	 */
	public java.lang.String getSstatus() {
		return getStr("sstatus");
	}

	/**
	 * 大楼:floor,物业:property，运营商:business;0:超级管理员
	 */
	public M setOrgType(java.lang.String orgType) {
		set("orgType", orgType);
		return (M)this;
	}
	
	/**
	 * 大楼:floor,物业:property，运营商:business;0:超级管理员
	 */
	public java.lang.String getOrgType() {
		return getStr("orgType");
	}

	/**
	 * 创建人姓名
	 */
	public M setRealName(java.lang.String realName) {
		set("realName", realName);
		return (M)this;
	}
	
	/**
	 * 创建人姓名
	 */
	public java.lang.String getRealName() {
		return getStr("realName");
	}

	/**
	 * 手机
	 */
	public M setPhone(java.lang.String phone) {
		set("phone", phone);
		return (M)this;
	}
	
	/**
	 * 手机
	 */
	public java.lang.String getPhone() {
		return getStr("phone");
	}

	/**
	 * 地址
	 */
	public M setAddr(java.lang.String addr) {
		set("addr", addr);
		return (M)this;
	}
	
	/**
	 * 地址
	 */
	public java.lang.String getAddr() {
		return getStr("addr");
	}

	/**
	 * 创建时间
	 */
	public M setCreateDate(java.lang.String createDate) {
		set("createDate", createDate);
		return (M)this;
	}
	
	/**
	 * 创建时间
	 */
	public java.lang.String getCreateDate() {
		return getStr("createDate");
	}

	/**
	 * 省
	 */
	public M setProvince(java.lang.String province) {
		set("province", province);
		return (M)this;
	}
	
	/**
	 * 省
	 */
	public java.lang.String getProvince() {
		return getStr("province");
	}

	/**
	 * 市区
	 */
	public M setCity(java.lang.String city) {
		set("city", city);
		return (M)this;
	}
	
	/**
	 * 市区
	 */
	public java.lang.String getCity() {
		return getStr("city");
	}

	/**
	 * 县
	 */
	public M setArea(java.lang.String area) {
		set("area", area);
		return (M)this;
	}
	
	/**
	 * 县
	 */
	public java.lang.String getArea() {
		return getStr("area");
	}

	/**
	 * 访问类型0：人脸识别1：二维码
	 */
	public M setAccessType(java.lang.String accessType) {
		set("accessType", accessType);
		return (M)this;
	}
	
	/**
	 * 访问类型0：人脸识别1：二维码
	 */
	public java.lang.String getAccessType() {
		return getStr("accessType");
	}

	/**
	 * app角色
	 */
	public M setApprole(java.lang.String approle) {
		set("approle", approle);
		return (M)this;
	}
	
	/**
	 * app角色
	 */
	public java.lang.String getApprole() {
		return getStr("approle");
	}

}
