package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseVCar<M extends BaseVCar<M>> extends Model<M> implements IBean {

	/**
	 * ????ͨ??ID
	 */
	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * ????ͨ??ID
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * ???ƺ
	 */
	public M setPlate(java.lang.String plate) {
		set("plate", plate);
		return (M)this;
	}
	
	/**
	 * ???ƺ
	 */
	public java.lang.String getPlate() {
		return getStr("plate");
	}

	/**
	 * ???????
	 */
	public M setVisitDate(java.lang.String visitDate) {
		set("visitDate", visitDate);
		return (M)this;
	}
	
	/**
	 * ???????
	 */
	public java.lang.String getVisitDate() {
		return getStr("visitDate");
	}

	/**
	 * ????ʱ?
	 */
	public M setVisitTime(java.lang.String visitTime) {
		set("visitTime", visitTime);
		return (M)this;
	}
	
	/**
	 * ????ʱ?
	 */
	public java.lang.String getVisitTime() {
		return getStr("visitTime");
	}

	/**
	 * ???ʼ?¼ID
	 */
	public M setVisitId(java.lang.Long visitId) {
		set("visitId", visitId);
		return (M)this;
	}
	
	/**
	 * ???ʼ?¼ID
	 */
	public java.lang.Long getVisitId() {
		return getLong("visitId");
	}

	/**
	 * ״̬ applyConfirm:?????У?applySuccess:???ܷ??ʣ?applyFail:?ܾ????
	 */
	public M setCStatus(java.lang.String cStatus) {
		set("cStatus", cStatus);
		return (M)this;
	}
	
	/**
	 * ״̬ applyConfirm:?????У?applySuccess:???ܷ??ʣ?applyFail:?ܾ????
	 */
	public java.lang.String getCStatus() {
		return getStr("cStatus");
	}

	/**
	 * ??????ID
	 */
	public M setApprovalUserId(java.lang.Long approvalUserId) {
		set("approvalUserId", approvalUserId);
		return (M)this;
	}
	
	/**
	 * ??????ID
	 */
	public java.lang.Long getApprovalUserId() {
		return getLong("approvalUserId");
	}

	public M setApprovalDateTime(java.lang.String approvalDateTime) {
		set("approvalDateTime", approvalDateTime);
		return (M)this;
	}
	
	public java.lang.String getApprovalDateTime() {
		return getStr("approvalDateTime");
	}

	/**
	 * 访问者手机号码
	 */
	public M setPhone(java.lang.String phone) {
		set("phone", phone);
		return (M)this;
	}
	
	/**
	 * 访问者手机号码
	 */
	public java.lang.String getPhone() {
		return getStr("phone");
	}

	/**
	 * 访问者姓名
	 */
	public M setUserName(java.lang.String userName) {
		set("userName", userName);
		return (M)this;
	}
	
	/**
	 * 访问者姓名
	 */
	public java.lang.String getUserName() {
		return getStr("userName");
	}

	/**
	 * 出入口
	 */
	public M setGate(java.lang.String gate) {
		set("gate", gate);
		return (M)this;
	}
	
	/**
	 * 出入口
	 */
	public java.lang.String getGate() {
		return getStr("gate");
	}

	/**
	 * 受访人ID
	 */
	public M setIntervieweeId(java.lang.Long intervieweeId) {
		set("intervieweeId", intervieweeId);
		return (M)this;
	}
	
	/**
	 * 受访人ID
	 */
	public java.lang.Long getIntervieweeId() {
		return getLong("intervieweeId");
	}

	/**
	 * 事由
	 */
	public M setReason(java.lang.String reason) {
		set("reason", reason);
		return (M)this;
	}
	
	/**
	 * 事由
	 */
	public java.lang.String getReason() {
		return getStr("reason");
	}

	/**
	 * 受访者姓名
	 */
	public M setVisitName(java.lang.String visitName) {
		set("visitName", visitName);
		return (M)this;
	}
	
	/**
	 * 受访者姓名
	 */
	public java.lang.String getVisitName() {
		return getStr("visitName");
	}

	/**
	 * 受访者手机号
	 */
	public M setVisitPhone(java.lang.String visitPhone) {
		set("visitPhone", visitPhone);
		return (M)this;
	}
	
	/**
	 * 受访者手机号
	 */
	public java.lang.String getVisitPhone() {
		return getStr("visitPhone");
	}

	/**
	 * 出入类型
	 */
	public M setInOutType(java.lang.Integer inOutType) {
		set("inOutType", inOutType);
		return (M)this;
	}
	
	/**
	 * 出入类型
	 */
	public java.lang.Integer getInOutType() {
		return getInt("inOutType");
	}

	/**
	 * 受访者单位
	 */
	public M setVisitDept(java.lang.String visitDept) {
		set("visitDept", visitDept);
		return (M)this;
	}
	
	/**
	 * 受访者单位
	 */
	public java.lang.String getVisitDept() {
		return getStr("visitDept");
	}

	/**
	 * 随车人数
	 */
	public M setNum(java.lang.Integer num) {
		set("num", num);
		return (M)this;
	}
	
	/**
	 * 随车人数
	 */
	public java.lang.Integer getNum() {
		return getInt("num");
	}

	/**
	 * 审批流程ID
	 */
	public M setProcessId(java.lang.String processId) {
		set("processId", processId);
		return (M)this;
	}
	
	/**
	 * 审批流程ID
	 */
	public java.lang.String getProcessId() {
		return getStr("processId");
	}

	/**
	 * 开始日期
	 */
	public M setStartDate(java.lang.String startDate) {
		set("startDate", startDate);
		return (M)this;
	}
	
	/**
	 * 开始日期
	 */
	public java.lang.String getStartDate() {
		return getStr("startDate");
	}

	/**
	 * 结束日期
	 */
	public M setEndDate(java.lang.String endDate) {
		set("endDate", endDate);
		return (M)this;
	}
	
	/**
	 * 结束日期
	 */
	public java.lang.String getEndDate() {
		return getStr("endDate");
	}

	/**
	 * 被访者回复
	 */
	public M setAnswerContent(java.lang.String answerContent) {
		set("answerContent", answerContent);
		return (M)this;
	}
	
	/**
	 * 被访者回复
	 */
	public java.lang.String getAnswerContent() {
		return getStr("answerContent");
	}

	/**
	 * 1--访问，2--邀约
	 */
	public M setRecordType(java.lang.Integer recordType) {
		set("recordType", recordType);
		return (M)this;
	}
	
	/**
	 * 1--访问，2--邀约
	 */
	public java.lang.Integer getRecordType() {
		return getInt("recordType");
	}

	/**
	 * 审核日期
	 */
	public M setReplyDate(java.lang.String replyDate) {
		set("replyDate", replyDate);
		return (M)this;
	}
	
	/**
	 * 审核日期
	 */
	public java.lang.String getReplyDate() {
		return getStr("replyDate");
	}

	/**
	 * 审核时间
	 */
	public M setReplyTime(java.lang.String replyTime) {
		set("replyTime", replyTime);
		return (M)this;
	}
	
	/**
	 * 审核时间
	 */
	public java.lang.String getReplyTime() {
		return getStr("replyTime");
	}

	/**
	 * 审核人ID
	 */
	public M setReplyUserId(java.lang.Long replyUserId) {
		set("replyUserId", replyUserId);
		return (M)this;
	}
	
	/**
	 * 审核人ID
	 */
	public java.lang.Long getReplyUserId() {
		return getLong("replyUserId");
	}

}
