package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseVLocalAuth<M extends BaseVLocalAuth<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 用户id
	 */
	public M setUserId(java.lang.Long userId) {
		set("userId", userId);
		return (M)this;
	}
	
	/**
	 * 用户id
	 */
	public java.lang.Long getUserId() {
		return getLong("userId");
	}

	/**
	 * 用户真实姓名
	 */
	public M setRealName(java.lang.String realName) {
		set("realName", realName);
		return (M)this;
	}
	
	/**
	 * 用户真实姓名
	 */
	public java.lang.String getRealName() {
		return getStr("realName");
	}

	/**
	 * 身份证号
	 */
	public M setIdNo(java.lang.String idNo) {
		set("idNo", idNo);
		return (M)this;
	}
	
	/**
	 * 身份证号
	 */
	public java.lang.String getIdNo() {
		return getStr("idNo");
	}

	/**
	 * 手持证件照
	 */
	public M setIdHandleImgUrl(java.lang.String idHandleImgUrl) {
		set("idHandleImgUrl", idHandleImgUrl);
		return (M)this;
	}
	
	/**
	 * 手持证件照
	 */
	public java.lang.String getIdHandleImgUrl() {
		return getStr("idHandleImgUrl");
	}

	/**
	 * 实名日期时间 yyyy-MM-dd hhmmss
	 */
	public M setAuthDate(java.lang.String authDate) {
		set("authDate", authDate);
		return (M)this;
	}
	
	/**
	 * 实名日期时间 yyyy-MM-dd hhmmss
	 */
	public java.lang.String getAuthDate() {
		return getStr("authDate");
	}

}
