package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseVAppYaoyueRecord<M extends BaseVAppYaoyueRecord<M>> extends Model<M> implements IBean {

	/**
	 * 主键ID
	 */
	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 主键ID
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 开始时间
	 */
	public M setVisitDate(java.lang.String visitDate) {
		set("visitDate", visitDate);
		return (M)this;
	}
	
	/**
	 * 开始时间
	 */
	public java.lang.String getVisitDate() {
		return getStr("visitDate");
	}

	/**
	 * 当前登录人登录账号
	 */
	public M setUserId(java.lang.String userId) {
		set("userId", userId);
		return (M)this;
	}
	
	/**
	 * 当前登录人登录账号
	 */
	public java.lang.String getUserId() {
		return getStr("userId");
	}

	/**
	 * 备注
	 */
	public M setReason(java.lang.String reason) {
		set("reason", reason);
		return (M)this;
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getReason() {
		return getStr("reason");
	}

	/**
	 * '状态 applying:申请中，applySuccess:接受访问，applyFail:拒绝访问',
	 */
	public M setCstatus(java.lang.String cstatus) {
		set("cstatus", cstatus);
		return (M)this;
	}
	
	/**
	 * '状态 applying:申请中，applySuccess:接受访问，applyFail:拒绝访问',
	 */
	public java.lang.String getCstatus() {
		return getStr("cstatus");
	}

	/**
	 * 操作人的当前时间
	 */
	public M setEndDate(java.lang.String endDate) {
		set("endDate", endDate);
		return (M)this;
	}
	
	/**
	 * 操作人的当前时间
	 */
	public java.lang.String getEndDate() {
		return getStr("endDate");
	}

	/**
	 * 结束时间
	 */
	public M setAnswerContent(java.lang.String answerContent) {
		set("answerContent", answerContent);
		return (M)this;
	}
	
	/**
	 * 结束时间
	 */
	public java.lang.String getAnswerContent() {
		return getStr("answerContent");
	}

	/**
	 * 手机号
	 */
	public M setOrgCode(java.lang.String orgCode) {
		set("orgCode", orgCode);
		return (M)this;
	}
	
	/**
	 * 手机号
	 */
	public java.lang.String getOrgCode() {
		return getStr("orgCode");
	}

	/**
	 * 当前登录人companyId
	 */
	public M setCompanyId(java.lang.Long companyId) {
		set("companyId", companyId);
		return (M)this;
	}
	
	/**
	 * 当前登录人companyId
	 */
	public java.lang.Long getCompanyId() {
		return getLong("companyId");
	}

	/**
	 * 名称
	 */
	public M setYaoyuetitle(java.lang.String yaoyuetitle) {
		set("yaoyuetitle", yaoyuetitle);
		return (M)this;
	}
	
	/**
	 * 名称
	 */
	public java.lang.String getYaoyuetitle() {
		return getStr("yaoyuetitle");
	}

	/**
	 * 邀请人姓名
	 */
	public M setAddusername(java.lang.String addusername) {
		set("addusername", addusername);
		return (M)this;
	}
	
	/**
	 * 邀请人姓名
	 */
	public java.lang.String getAddusername() {
		return getStr("addusername");
	}

	/**
	 * 扩展字段1
	 */
	public M setExp1(java.lang.String exp1) {
		set("exp1", exp1);
		return (M)this;
	}
	
	/**
	 * 扩展字段1
	 */
	public java.lang.String getExp1() {
		return getStr("exp1");
	}

	/**
	 * 扩展字段2
	 */
	public M setExp2(java.lang.String exp2) {
		set("exp2", exp2);
		return (M)this;
	}
	
	/**
	 * 扩展字段2
	 */
	public java.lang.String getExp2() {
		return getStr("exp2");
	}

}
