package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseActHiTaskinst<M extends BaseActHiTaskinst<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("ID_", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("ID_");
	}

	public M setProcDefId(java.lang.String procDefId) {
		set("PROC_DEF_ID_", procDefId);
		return (M)this;
	}
	
	public java.lang.String getProcDefId() {
		return getStr("PROC_DEF_ID_");
	}

	public M setTaskDefKey(java.lang.String taskDefKey) {
		set("TASK_DEF_KEY_", taskDefKey);
		return (M)this;
	}
	
	public java.lang.String getTaskDefKey() {
		return getStr("TASK_DEF_KEY_");
	}

	public M setProcInstId(java.lang.String procInstId) {
		set("PROC_INST_ID_", procInstId);
		return (M)this;
	}
	
	public java.lang.String getProcInstId() {
		return getStr("PROC_INST_ID_");
	}

	public M setExecutionId(java.lang.String executionId) {
		set("EXECUTION_ID_", executionId);
		return (M)this;
	}
	
	public java.lang.String getExecutionId() {
		return getStr("EXECUTION_ID_");
	}

	public M setName(java.lang.String name) {
		set("NAME_", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("NAME_");
	}

	public M setParentTaskId(java.lang.String parentTaskId) {
		set("PARENT_TASK_ID_", parentTaskId);
		return (M)this;
	}
	
	public java.lang.String getParentTaskId() {
		return getStr("PARENT_TASK_ID_");
	}

	public M setDescription(java.lang.String description) {
		set("DESCRIPTION_", description);
		return (M)this;
	}
	
	public java.lang.String getDescription() {
		return getStr("DESCRIPTION_");
	}

	public M setOwner(java.lang.String owner) {
		set("OWNER_", owner);
		return (M)this;
	}
	
	public java.lang.String getOwner() {
		return getStr("OWNER_");
	}

	public M setAssignee(java.lang.String assignee) {
		set("ASSIGNEE_", assignee);
		return (M)this;
	}
	
	public java.lang.String getAssignee() {
		return getStr("ASSIGNEE_");
	}

	public M setStartTime(java.util.Date startTime) {
		set("START_TIME_", startTime);
		return (M)this;
	}
	
	public java.util.Date getStartTime() {
		return get("START_TIME_");
	}

	public M setClaimTime(java.util.Date claimTime) {
		set("CLAIM_TIME_", claimTime);
		return (M)this;
	}
	
	public java.util.Date getClaimTime() {
		return get("CLAIM_TIME_");
	}

	public M setEndTime(java.util.Date endTime) {
		set("END_TIME_", endTime);
		return (M)this;
	}
	
	public java.util.Date getEndTime() {
		return get("END_TIME_");
	}

	public M setDuration(java.lang.Long duration) {
		set("DURATION_", duration);
		return (M)this;
	}
	
	public java.lang.Long getDuration() {
		return getLong("DURATION_");
	}

	public M setDeleteReason(java.lang.String deleteReason) {
		set("DELETE_REASON_", deleteReason);
		return (M)this;
	}
	
	public java.lang.String getDeleteReason() {
		return getStr("DELETE_REASON_");
	}

	public M setPriority(java.lang.Integer priority) {
		set("PRIORITY_", priority);
		return (M)this;
	}
	
	public java.lang.Integer getPriority() {
		return getInt("PRIORITY_");
	}

	public M setDueDate(java.util.Date dueDate) {
		set("DUE_DATE_", dueDate);
		return (M)this;
	}
	
	public java.util.Date getDueDate() {
		return get("DUE_DATE_");
	}

	public M setFormKey(java.lang.String formKey) {
		set("FORM_KEY_", formKey);
		return (M)this;
	}
	
	public java.lang.String getFormKey() {
		return getStr("FORM_KEY_");
	}

	public M setCategory(java.lang.String category) {
		set("CATEGORY_", category);
		return (M)this;
	}
	
	public java.lang.String getCategory() {
		return getStr("CATEGORY_");
	}

	public M setTenantId(java.lang.String tenantId) {
		set("TENANT_ID_", tenantId);
		return (M)this;
	}
	
	public java.lang.String getTenantId() {
		return getStr("TENANT_ID_");
	}

}
