package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseActRuJob<M extends BaseActRuJob<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("ID_", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("ID_");
	}

	public M setRev(java.lang.Integer rev) {
		set("REV_", rev);
		return (M)this;
	}
	
	public java.lang.Integer getRev() {
		return getInt("REV_");
	}

	public M setType(java.lang.String type) {
		set("TYPE_", type);
		return (M)this;
	}
	
	public java.lang.String getType() {
		return getStr("TYPE_");
	}

	public M setLockExpTime(java.util.Date lockExpTime) {
		set("LOCK_EXP_TIME_", lockExpTime);
		return (M)this;
	}
	
	public java.util.Date getLockExpTime() {
		return get("LOCK_EXP_TIME_");
	}

	public M setLockOwner(java.lang.String lockOwner) {
		set("LOCK_OWNER_", lockOwner);
		return (M)this;
	}
	
	public java.lang.String getLockOwner() {
		return getStr("LOCK_OWNER_");
	}

	public M setExclusive(java.lang.Boolean exclusive) {
		set("EXCLUSIVE_", exclusive);
		return (M)this;
	}
	
	public java.lang.Boolean getExclusive() {
		return get("EXCLUSIVE_");
	}

	public M setExecutionId(java.lang.String executionId) {
		set("EXECUTION_ID_", executionId);
		return (M)this;
	}
	
	public java.lang.String getExecutionId() {
		return getStr("EXECUTION_ID_");
	}

	public M setProcessInstanceId(java.lang.String processInstanceId) {
		set("PROCESS_INSTANCE_ID_", processInstanceId);
		return (M)this;
	}
	
	public java.lang.String getProcessInstanceId() {
		return getStr("PROCESS_INSTANCE_ID_");
	}

	public M setProcDefId(java.lang.String procDefId) {
		set("PROC_DEF_ID_", procDefId);
		return (M)this;
	}
	
	public java.lang.String getProcDefId() {
		return getStr("PROC_DEF_ID_");
	}

	public M setRetries(java.lang.Integer retries) {
		set("RETRIES_", retries);
		return (M)this;
	}
	
	public java.lang.Integer getRetries() {
		return getInt("RETRIES_");
	}

	public M setExceptionStackId(java.lang.String exceptionStackId) {
		set("EXCEPTION_STACK_ID_", exceptionStackId);
		return (M)this;
	}
	
	public java.lang.String getExceptionStackId() {
		return getStr("EXCEPTION_STACK_ID_");
	}

	public M setExceptionMsg(java.lang.String exceptionMsg) {
		set("EXCEPTION_MSG_", exceptionMsg);
		return (M)this;
	}
	
	public java.lang.String getExceptionMsg() {
		return getStr("EXCEPTION_MSG_");
	}

	public M setDuedate(java.util.Date duedate) {
		set("DUEDATE_", duedate);
		return (M)this;
	}
	
	public java.util.Date getDuedate() {
		return get("DUEDATE_");
	}

	public M setRepeat(java.lang.String repeat) {
		set("REPEAT_", repeat);
		return (M)this;
	}
	
	public java.lang.String getRepeat() {
		return getStr("REPEAT_");
	}

	public M setHandlerType(java.lang.String handlerType) {
		set("HANDLER_TYPE_", handlerType);
		return (M)this;
	}
	
	public java.lang.String getHandlerType() {
		return getStr("HANDLER_TYPE_");
	}

	public M setHandlerCfg(java.lang.String handlerCfg) {
		set("HANDLER_CFG_", handlerCfg);
		return (M)this;
	}
	
	public java.lang.String getHandlerCfg() {
		return getStr("HANDLER_CFG_");
	}

	public M setTenantId(java.lang.String tenantId) {
		set("TENANT_ID_", tenantId);
		return (M)this;
	}
	
	public java.lang.String getTenantId() {
		return getStr("TENANT_ID_");
	}

}
