package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseVDeviceWincc<M extends BaseVDeviceWincc<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setWinccName(java.lang.String winccName) {
		set("winccName", winccName);
		return (M)this;
	}
	
	public java.lang.String getWinccName() {
		return getStr("winccName");
	}

	public M setWinccIP(java.lang.String winccIP) {
		set("winccIP", winccIP);
		return (M)this;
	}
	
	public java.lang.String getWinccIP() {
		return getStr("winccIP");
	}

	public M setOrgName(java.lang.String orgName) {
		set("orgName", orgName);
		return (M)this;
	}
	
	public java.lang.String getOrgName() {
		return getStr("orgName");
	}

	public M setOrgCode(java.lang.String orgCode) {
		set("orgCode", orgCode);
		return (M)this;
	}
	
	public java.lang.String getOrgCode() {
		return getStr("orgCode");
	}

	public M setStatus(java.lang.String status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}

	public M setExpt1(java.lang.String expt1) {
		set("expt1", expt1);
		return (M)this;
	}
	
	public java.lang.String getExpt1() {
		return getStr("expt1");
	}

	public M setExpt2(java.lang.String expt2) {
		set("expt2", expt2);
		return (M)this;
	}
	
	public java.lang.String getExpt2() {
		return getStr("expt2");
	}

}
