package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTblAccess<M extends BaseTblAccess<M>> extends Model<M> implements IBean {

	/**
	 * 门禁表
	 */
	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 门禁表
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 门禁名称
	 */
	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	/**
	 * 门禁名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 门禁状态：1-启用；2-禁用；3-删除
	 */
	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}
	
	/**
	 * 门禁状态：1-启用；2-禁用；3-删除
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	/**
	 * 创建时间
	 */
	public M setCreateTime(java.lang.String createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	/**
	 * 创建时间
	 */
	public java.lang.String getCreateTime() {
		return getStr("create_time");
	}

	/**
	 * 更新时间
	 */
	public M setUpdateTime(java.lang.String updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	/**
	 * 更新时间
	 */
	public java.lang.String getUpdateTime() {
		return getStr("update_time");
	}

	/**
	 * 门禁编码
	 */
	public M setAccessCode(java.lang.String accessCode) {
		set("access_code", accessCode);
		return (M)this;
	}
	
	/**
	 * 门禁编码
	 */
	public java.lang.String getAccessCode() {
		return getStr("access_code");
	}

	/**
	 * 创建者公司
	 */
	public M setOrgId(java.lang.Long orgId) {
		set("org_id", orgId);
		return (M)this;
	}
	
	/**
	 * 创建者公司
	 */
	public java.lang.Long getOrgId() {
		return getLong("org_id");
	}

	/**
	 *  是否对外开放：0-否；1-是
	 */
	public M setIsOpen(java.lang.Integer isOpen) {
		set("is_open", isOpen);
		return (M)this;
	}
	
	/**
	 *  是否对外开放：0-否；1-是
	 */
	public java.lang.Integer getIsOpen() {
		return getInt("is_open");
	}

}
