package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseVDictionaries<M extends BaseVDictionaries<M>> extends Model<M> implements IBean {

	public M setId(Long id) {
		set("id", id);
		return (M)this;
	}

	public Long getId() {
		return getLong("id");
	}

	public M setDictionariesName(String dictionariesName) {
		set("dictionaries_name", dictionariesName);
		return (M)this;
	}

	public String getDictionariesName() {
		return getStr("dictionaries_name");
	}

	public M setDictionariesKey(String dictionariesKey) {
		set("dictionaries_key", dictionariesKey);
		return (M)this;
	}

	public String getDictionariesKey() {
		return getStr("dictionaries_key");
	}

	public M setDictionariesValue(String dictionariesValue) {
		set("dictionaries_value", dictionariesValue);
		return (M)this;
	}

	public String getDictionariesValue() {
		return getStr("dictionaries_value");
	}

	public M setExtra1(String extra1) {
		set("extra1", extra1);
		return (M)this;
	}

	public String getExtra1() {
		return getStr("extra1");
	}

	public M setExtra2(String extra2) {
		set("extra2", extra2);
		return (M)this;
	}

	public String getExtra2() {
		return getStr("extra2");
	}

	public M setExtra3(String extra3) {
		set("extra3", extra3);
		return (M)this;
	}

	public String getExtra3() {
		return getStr("extra3");
	}

}
