package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseVDept<M extends BaseVDept<M>> extends Model<M> implements IBean {

	/**
	 * 原company_section表
	 */
	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 原company_section表
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 大楼号
	 */
	public M setOrgId(java.lang.Long orgId) {
		set("org_id", orgId);
		return (M)this;
	}
	
	/**
	 * 大楼号
	 */
	public java.lang.Long getOrgId() {
		return getLong("org_id");
	}

	/**
	 * 部门编码
	 */
	public M setCode(java.lang.String code) {
		set("code", code);
		return (M)this;
	}
	
	/**
	 * 部门编码
	 */
	public java.lang.String getCode() {
		return getStr("code");
	}

	/**
	 * 部门名称
	 */
	public M setDeptName(java.lang.String deptName) {
		set("dept_name", deptName);
		return (M)this;
	}
	
	/**
	 * 部门名称
	 */
	public java.lang.String getDeptName() {
		return getStr("dept_name");
	}

	/**
	 * 楼层
	 */
	public M setFloor(java.lang.String floor) {
		set("floor", floor);
		return (M)this;
	}
	
	/**
	 * 楼层
	 */
	public java.lang.String getFloor() {
		return getStr("floor");
	}

	/**
	 * 部门主管id 去dept_user 查询
	 */
	public M setManageUserId(java.lang.Long manageUserId) {
		set("manage_user_id", manageUserId);
		return (M)this;
	}
	
	/**
	 * 部门主管id 去dept_user 查询
	 */
	public java.lang.Long getManageUserId() {
		return getLong("manage_user_id");
	}

}
