package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseVDVisitorInout<M extends BaseVDVisitorInout<M>> extends Model<M> implements IBean {

	/**
	 * 访客管理
	 */
	public M setId(Long id) {
		set("id", id);
		return (M)this;
	}

	/**
	 * 访客管理
	 */
	public Long getId() {
		return getLong("id");
	}

	/**
	 * 大楼编号
	 */
	public M setOrgCode(String orgCode) {
		set("orgCode", orgCode);
		return (M)this;
	}

	/**
	 * 大楼编号
	 */
	public String getOrgCode() {
		return getStr("orgCode");
	}

	/**
	 * 上位机编号
	 */
	public M setPospCode(String pospCode) {
		set("pospCode", pospCode);
		return (M)this;
	}

	/**
	 * 上位机编号
	 */
	public String getPospCode() {
		return getStr("pospCode");
	}

	/**
	 * 设备扫描日期：yyyy:MM:dd
	 */
	public M setScanDate(String scanDate) {
		set("scanDate", scanDate);
		return (M)this;
	}

	/**
	 * 设备扫描日期：yyyy:MM:dd
	 */
	public String getScanDate() {
		return getStr("scanDate");
	}

	/**
	 * 设备扫描时间：HH:mm:ss
	 */
	public M setScanTime(String scanTime) {
		set("scanTime", scanTime);
		return (M)this;
	}

	/**
	 * 设备扫描时间：HH:mm:ss
	 */
	public String getScanTime() {
		return getStr("scanTime");
	}

	/**
	 * 进出类型：in/out
	 */
	public M setInOrOut(String inOrOut) {
		set("inOrOut", inOrOut);
		return (M)this;
	}

	/**
	 * 进出类型：in/out
	 */
	public String getInOrOut() {
		return getStr("inOrOut");
	}

	/**
	 * 通道编号
	 */
	public M setOutNumber(String outNumber) {
		set("outNumber", outNumber);
		return (M)this;
	}

	/**
	 * 通道编号
	 */
	public String getOutNumber() {
		return getStr("outNumber");
	}

	/**
	 * 通行设备的类型：QRCODE/FACE
	 */
	public M setDeviceType(String deviceType) {
		set("deviceType", deviceType);
		return (M)this;
	}

	/**
	 * 通行设备的类型：QRCODE/FACE
	 */
	public String getDeviceType() {
		return getStr("deviceType");
	}

	/**
	 * 设备的IP地址
	 */
	public M setDeviceIp(String deviceIp) {
		set("deviceIp", deviceIp);
		return (M)this;
	}

	/**
	 * 设备的IP地址
	 */
	public String getDeviceIp() {
		return getStr("deviceIp");
	}

	/**
	 * 通行人员类型：staff/visitor
	 */
	public M setUserType(String userType) {
		set("userType", userType);
		return (M)this;
	}

	/**
	 * 通行人员类型：staff/visitor
	 */
	public String getUserType() {
		return getStr("userType");
	}

	/**
	 * 通行人员名字
	 */
	public M setUserName(String userName) {
		set("userName", userName);
		return (M)this;
	}

	/**
	 * 通行人员名字
	 */
	public String getUserName() {
		return getStr("userName");
	}

	/**
	 * 通行人员证件号
	 */
	public M setIdCard(String idCard) {
		set("idCard", idCard);
		return (M)this;
	}

	/**
	 * 通行人员证件号
	 */
	public String getIdCard() {
		return getStr("idCard");
	}

	/**
	 * 发送记录的标识：已发送(T)/未发送(F)
	 */
	public M setIsSendFlag(String isSendFlag) {
		set("isSendFlag", isSendFlag);
		return (M)this;
	}

	/**
	 * 发送记录的标识：已发送(T)/未发送(F)
	 */
	public String getIsSendFlag() {
		return getStr("isSendFlag");
	}

	/**
	 * 拓展字段1
	 */
	public M setExpt1(String expt1) {
		set("expt1", expt1);
		return (M)this;
	}

	/**
	 * 拓展字段1
	 */
	public String getExpt1() {
		return getStr("expt1");
	}

	/**
	 * 拓展字段2
	 */
	public M setExpt2(String expt2) {
		set("expt2", expt2);
		return (M)this;
	}

	/**
	 * 拓展字段2
	 */
	public String getExpt2() {
		return getStr("expt2");
	}

}
