package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseVAppRoleMenu<M extends BaseVAppRoleMenu<M>> extends Model<M> implements IBean {

	/**
	 * id
	 */
	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * id
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 角色id
	 */
	public M setRoleId(java.lang.Long roleId) {
		set("role_id", roleId);
		return (M)this;
	}
	
	/**
	 * 角色id
	 */
	public java.lang.Long getRoleId() {
		return getLong("role_id");
	}

	/**
	 * 菜单id
	 */
	public M setMenuId(java.lang.Long menuId) {
		set("menu_id", menuId);
		return (M)this;
	}
	
	/**
	 * 菜单id
	 */
	public java.lang.Long getMenuId() {
		return getLong("menu_id");
	}

	/**
	 * T--开启  F--未开启
	 */
	public M setIsOpen(java.lang.String isOpen) {
		set("isOpen", isOpen);
		return (M)this;
	}
	
	/**
	 * T--开启  F--未开启
	 */
	public java.lang.String getIsOpen() {
		return getStr("isOpen");
	}

	/**
	 * 更新时间
	 */
	public M setUpdateTime(java.lang.String updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	/**
	 * 更新时间
	 */
	public java.lang.String getUpdateTime() {
		return getStr("update_time");
	}

	/**
	 * 操作者id
	 */
	public M setOperatorId(java.lang.Long operatorId) {
		set("operator_id", operatorId);
		return (M)this;
	}
	
	/**
	 * 操作者id
	 */
	public java.lang.Long getOperatorId() {
		return getLong("operator_id");
	}

	/**
	 * 拓展字段1
	 */
	public M setExt1(java.lang.String ext1) {
		set("ext1", ext1);
		return (M)this;
	}
	
	/**
	 * 拓展字段1
	 */
	public java.lang.String getExt1() {
		return getStr("ext1");
	}

	/**
	 * 拓展字段2
	 */
	public M setExt2(java.lang.String ext2) {
		set("ext2", ext2);
		return (M)this;
	}
	
	/**
	 * 拓展字段2
	 */
	public java.lang.String getExt2() {
		return getStr("ext2");
	}

	/**
	 * 拓展字段3
	 */
	public M setExt3(java.lang.String ext3) {
		set("ext3", ext3);
		return (M)this;
	}
	
	/**
	 * 拓展字段3
	 */
	public java.lang.String getExt3() {
		return getStr("ext3");
	}

}
