package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTblSmsTemplate<M extends BaseTblSmsTemplate<M>> extends Model<M> implements IBean {

	/**
	 * 短信模板id
	 */
	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 短信模板id
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 模板消息
	 */
	public M setContent(java.lang.String content) {
		set("content", content);
		return (M)this;
	}
	
	/**
	 * 模板消息
	 */
	public java.lang.String getContent() {
		return getStr("content");
	}

	/**
	 * 用户
	 */
	public M setUser(java.lang.String user) {
		set("user", user);
		return (M)this;
	}
	
	/**
	 * 用户
	 */
	public java.lang.String getUser() {
		return getStr("user");
	}

	/**
	 * 阿里云模板code
	 */
	public M setCode(java.lang.String code) {
		set("code", code);
		return (M)this;
	}
	
	/**
	 * 阿里云模板code
	 */
	public java.lang.String getCode() {
		return getStr("code");
	}

	/**
	 * 模板名
	 */
	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	/**
	 * 模板名
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setSign(java.lang.String sign) {
		set("sign", sign);
		return (M)this;
	}
	
	public java.lang.String getSign() {
		return getStr("sign");
	}

}
