package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseVKey<M extends BaseVKey<M>> extends Model<M> implements IBean {

	public M setId(Long id) {
		set("id", id);
		return (M)this;
	}

	public Long getId() {
		return getLong("id");
	}

	public M setPrivateKey(String privateKey) {
		set("private_key", privateKey);
		return (M)this;
	}

	public String getPrivateKey() {
		return getStr("private_key");
	}

	public M setPublicKey(String publicKey) {
		set("public_key", publicKey);
		return (M)this;
	}

	public String getPublicKey() {
		return getStr("public_key");
	}

	public M setStatus(String status) {
		set("status", status);
		return (M)this;
	}

	public String getStatus() {
		return getStr("status");
	}

	public M setCreatetime(String createtime) {
		set("createtime", createtime);
		return (M)this;
	}

	public String getCreatetime() {
		return getStr("createtime");
	}

	public M setExtra1(String extra1) {
		set("extra1", extra1);
		return (M)this;
	}

	public String getExtra1() {
		return getStr("extra1");
	}

	public M setExtra2(String extra2) {
		set("extra2", extra2);
		return (M)this;
	}

	public String getExtra2() {
		return getStr("extra2");
	}

	public M setExtra3(String extra3) {
		set("extra3", extra3);
		return (M)this;
	}

	public String getExtra3() {
		return getStr("extra3");
	}

}
