package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseVOutVisitor<M extends BaseVOutVisitor<M>> extends Model<M> implements IBean {

	/**
	 * 企业版外部映射
	 */
	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 企业版外部映射
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 企业内部员工唯一标识，根据某种算法获取，如身份证截取前6位后6位+手机号+姓名
	 */
	public M setUserCode(java.lang.String userCode) {
		set("userCode", userCode);
		return (M)this;
	}
	
	/**
	 * 企业内部员工唯一标识，根据某种算法获取，如身份证截取前6位后6位+手机号+姓名
	 */
	public java.lang.String getUserCode() {
		return getStr("userCode");
	}

	/**
	 * 真实姓名
	 */
	public M setRealName(java.lang.String realName) {
		set("realName", realName);
		return (M)this;
	}
	
	/**
	 * 真实姓名
	 */
	public java.lang.String getRealName() {
		return getStr("realName");
	}

	/**
	 * 手机号码
	 */
	public M setPhone(java.lang.String phone) {
		set("phone", phone);
		return (M)this;
	}
	
	/**
	 * 手机号码
	 */
	public java.lang.String getPhone() {
		return getStr("phone");
	}

	/**
	 * 是否实人认证 T F
	 */
	public M setIsAuth(java.lang.String isAuth) {
		set("isAuth", isAuth);
		return (M)this;
	}
	
	/**
	 * 是否实人认证 T F
	 */
	public java.lang.String getIsAuth() {
		return getStr("isAuth");
	}

	/**
	 * 手持证件地址
	 */
	public M setIdHandleImgUrl(java.lang.String idHandleImgUrl) {
		set("idHandleImgUrl", idHandleImgUrl);
		return (M)this;
	}
	
	/**
	 * 手持证件地址
	 */
	public java.lang.String getIdHandleImgUrl() {
		return getStr("idHandleImgUrl");
	}

	/**
	 * 创建时间
	 */
	public M setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
		return (M)this;
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	/**
	 * 拓展字段1
	 */
	public M setExt1(java.lang.String ext1) {
		set("ext1", ext1);
		return (M)this;
	}
	
	/**
	 * 拓展字段1
	 */
	public java.lang.String getExt1() {
		return getStr("ext1");
	}

	/**
	 * 拓展字段2
	 */
	public M setExt2(java.lang.String ext2) {
		set("ext2", ext2);
		return (M)this;
	}
	
	/**
	 * 拓展字段2
	 */
	public java.lang.String getExt2() {
		return getStr("ext2");
	}

	/**
	 * 拓展字段3
	 */
	public M setExt3(java.lang.String ext3) {
		set("ext3", ext3);
		return (M)this;
	}
	
	/**
	 * 拓展字段3
	 */
	public java.lang.String getExt3() {
		return getStr("ext3");
	}

}
