package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseVBusiness<M extends BaseVBusiness<M>> extends Model<M> implements IBean {

	public M setId(Long id) {
		set("id", id);
		return (M)this;
	}

	public Long getId() {
		return getLong("id");
	}

	/**
	 * 商家店名
	 */
	public M setBusinessName(String businessName) {
		set("business_name", businessName);
		return (M)this;
	}

	/**
	 * 商家店名
	 */
	public String getBusinessName() {
		return getStr("business_name");
	}

	/**
	 * 电话
	 */
	public M setTel(String tel) {
		set("tel", tel);
		return (M)this;
	}

	/**
	 * 电话
	 */
	public String getTel() {
		return getStr("tel");
	}

	/**
	 * 真实姓名
	 */
	public M setTrueName(String trueName) {
		set("true_name", trueName);
		return (M)this;
	}

	/**
	 * 真实姓名
	 */
	public String getTrueName() {
		return getStr("true_name");
	}

	/**
	 * 创建时间
	 */
	public M setCreatetime(byte[] createtime) {
		set("createtime", createtime);
		return (M)this;
	}

	/**
	 * 创建时间
	 */
	public byte[] getCreatetime() {
		return get("createtime");
	}

	public M setExtra1(String extra1) {
		set("extra1", extra1);
		return (M)this;
	}

	public String getExtra1() {
		return getStr("extra1");
	}

	public M setExtra2(String extra2) {
		set("extra2", extra2);
		return (M)this;
	}

	public String getExtra2() {
		return getStr("extra2");
	}

	public M setExtra3(String extra3) {
		set("extra3", extra3);
		return (M)this;
	}

	public String getExtra3() {
		return getStr("extra3");
	}

}
