package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseVBlackUser<M extends BaseVBlackUser<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 名字
	 */
	public M setRealName(java.lang.String realName) {
		set("realName", realName);
		return (M)this;
	}
	
	/**
	 * 名字
	 */
	public java.lang.String getRealName() {
		return getStr("realName");
	}

	/**
	 * 身份证号码
	 */
	public M setIdCard(java.lang.String idCard) {
		set("idCard", idCard);
		return (M)this;
	}
	
	/**
	 * 身份证号码
	 */
	public java.lang.String getIdCard() {
		return getStr("idCard");
	}

	/**
	 * 手机号
	 */
	public M setPhone(java.lang.String phone) {
		set("phone", phone);
		return (M)this;
	}
	
	/**
	 * 手机号
	 */
	public java.lang.String getPhone() {
		return getStr("phone");
	}

	public M setPhoto(java.lang.String photo) {
		set("photo", photo);
		return (M)this;
	}
	
	public java.lang.String getPhoto() {
		return getStr("photo");
	}

	/**
	 * 级别(1-高，2-中，3-低)
	 */
	public M setLevel(java.lang.String level) {
		set("level", level);
		return (M)this;
	}
	
	/**
	 * 级别(1-高，2-中，3-低)
	 */
	public java.lang.String getLevel() {
		return getStr("level");
	}

	/**
	 * 类型
	 */
	public M setUserType(java.lang.String userType) {
		set("userType", userType);
		return (M)this;
	}
	
	/**
	 * 类型
	 */
	public java.lang.String getUserType() {
		return getStr("userType");
	}

	/**
	 * 创建时间
	 */
	public M setCreateDate(java.lang.String createDate) {
		set("createDate", createDate);
		return (M)this;
	}
	
	/**
	 * 创建时间
	 */
	public java.lang.String getCreateDate() {
		return getStr("createDate");
	}

	/**
	 * 拓展字段
	 */
	public M setExpt1(java.lang.String expt1) {
		set("expt1", expt1);
		return (M)this;
	}
	
	/**
	 * 拓展字段
	 */
	public java.lang.String getExpt1() {
		return getStr("expt1");
	}

	/**
	 * 拓展字段
	 */
	public M setExpt2(java.lang.String expt2) {
		set("expt2", expt2);
		return (M)this;
	}
	
	/**
	 * 拓展字段
	 */
	public java.lang.String getExpt2() {
		return getStr("expt2");
	}

}
