package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseActRuVariable<M extends BaseActRuVariable<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("ID_", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("ID_");
	}

	public M setRev(java.lang.Integer rev) {
		set("REV_", rev);
		return (M)this;
	}
	
	public java.lang.Integer getRev() {
		return getInt("REV_");
	}

	public M setType(java.lang.String type) {
		set("TYPE_", type);
		return (M)this;
	}
	
	public java.lang.String getType() {
		return getStr("TYPE_");
	}

	public M setName(java.lang.String name) {
		set("NAME_", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("NAME_");
	}

	public M setExecutionId(java.lang.String executionId) {
		set("EXECUTION_ID_", executionId);
		return (M)this;
	}
	
	public java.lang.String getExecutionId() {
		return getStr("EXECUTION_ID_");
	}

	public M setProcInstId(java.lang.String procInstId) {
		set("PROC_INST_ID_", procInstId);
		return (M)this;
	}
	
	public java.lang.String getProcInstId() {
		return getStr("PROC_INST_ID_");
	}

	public M setTaskId(java.lang.String taskId) {
		set("TASK_ID_", taskId);
		return (M)this;
	}
	
	public java.lang.String getTaskId() {
		return getStr("TASK_ID_");
	}

	public M setBytearrayId(java.lang.String bytearrayId) {
		set("BYTEARRAY_ID_", bytearrayId);
		return (M)this;
	}
	
	public java.lang.String getBytearrayId() {
		return getStr("BYTEARRAY_ID_");
	}

	public M setDouble(java.lang.Double _double) {
		set("DOUBLE_", _double);
		return (M)this;
	}
	
	public java.lang.Double getDouble() {
		return getDouble("DOUBLE_");
	}

	public M setLong(java.lang.Long _long) {
		set("LONG_", _long);
		return (M)this;
	}
	
	public java.lang.Long getLong() {
		return getLong("LONG_");
	}

	public M setText(java.lang.String text) {
		set("TEXT_", text);
		return (M)this;
	}
	
	public java.lang.String getText() {
		return getStr("TEXT_");
	}

	public M setText2(java.lang.String text2) {
		set("TEXT2_", text2);
		return (M)this;
	}
	
	public java.lang.String getText2() {
		return getStr("TEXT2_");
	}

}
