package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseVAppCheckintime<M extends BaseVAppCheckintime<M>> extends Model<M> implements IBean {

	/**
	 * 考勤打卡
	 */
	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 考勤打卡
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 上班时间，表示为距离当天0点的秒数。
	 */
	public M setWorkSec(java.lang.Integer workSec) {
		set("work_sec", workSec);
		return (M)this;
	}
	
	/**
	 * 上班时间，表示为距离当天0点的秒数。
	 */
	public java.lang.Integer getWorkSec() {
		return getInt("work_sec");
	}

	/**
	 * 下班时间，表示为距离当天0点的秒数。
	 */
	public M setOffWorkSec(java.lang.Integer offWorkSec) {
		set("off_work_sec", offWorkSec);
		return (M)this;
	}
	
	/**
	 * 下班时间，表示为距离当天0点的秒数。
	 */
	public java.lang.Integer getOffWorkSec() {
		return getInt("off_work_sec");
	}

	/**
	 * 上班提醒时间，表示为距离当天0点的秒数。
	 */
	public M setRemindWorkSec(java.lang.Integer remindWorkSec) {
		set("remind_work_sec", remindWorkSec);
		return (M)this;
	}
	
	/**
	 * 上班提醒时间，表示为距离当天0点的秒数。
	 */
	public java.lang.Integer getRemindWorkSec() {
		return getInt("remind_work_sec");
	}

	/**
	 * 下班提醒时间，表示为距离当天0点的秒数。
	 */
	public M setRemindOffWorkSec(java.lang.Integer remindOffWorkSec) {
		set("remind_off_work_sec", remindOffWorkSec);
		return (M)this;
	}
	
	/**
	 * 下班提醒时间，表示为距离当天0点的秒数。
	 */
	public java.lang.Integer getRemindOffWorkSec() {
		return getInt("remind_off_work_sec");
	}

}
