package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseVUserAuth<M extends BaseVUserAuth<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 父节点id
	 */
	public M setParentId(java.lang.Long parentId) {
		set("parent_id", parentId);
		return (M)this;
	}
	
	/**
	 * 父节点id
	 */
	public java.lang.Long getParentId() {
		return getLong("parent_id");
	}

	/**
	 * 权限名称
	 */
	public M setAuthName(java.lang.String authName) {
		set("auth_name", authName);
		return (M)this;
	}
	
	/**
	 * 权限名称
	 */
	public java.lang.String getAuthName() {
		return getStr("auth_name");
	}

	/**
	 * 创建时间
	 */
	public M setCreatetime(java.lang.String createtime) {
		set("createtime", createtime);
		return (M)this;
	}
	
	/**
	 * 创建时间
	 */
	public java.lang.String getCreatetime() {
		return getStr("createtime");
	}

	/**
	 * 描述
	 */
	public M setDescription(java.lang.String description) {
		set("description", description);
		return (M)this;
	}
	
	/**
	 * 描述
	 */
	public java.lang.String getDescription() {
		return getStr("description");
	}

}
