package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseVNews<M extends BaseVNews<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 日期
	 */
	public M setNewsDate(java.lang.String newsDate) {
		set("newsDate", newsDate);
		return (M)this;
	}
	
	/**
	 * 日期
	 */
	public java.lang.String getNewsDate() {
		return getStr("newsDate");
	}

	/**
	 * 标题
	 */
	public M setNewsName(java.lang.String newsName) {
		set("newsName", newsName);
		return (M)this;
	}
	
	/**
	 * 标题
	 */
	public java.lang.String getNewsName() {
		return getStr("newsName");
	}

	/**
	 * 简单描述
	 */
	public M setNewsDetail(java.lang.String newsDetail) {
		set("newsDetail", newsDetail);
		return (M)this;
	}
	
	/**
	 * 简单描述
	 */
	public java.lang.String getNewsDetail() {
		return getStr("newsDetail");
	}

	/**
	 * 图片(图片服务器)
	 */
	public M setNewsImageUrl(java.lang.String newsImageUrl) {
		set("newsImageUrl", newsImageUrl);
		return (M)this;
	}
	
	/**
	 * 图片(图片服务器)
	 */
	public java.lang.String getNewsImageUrl() {
		return getStr("newsImageUrl");
	}

	/**
	 * 跳转URL
	 */
	public M setNewsUrl(java.lang.String newsUrl) {
		set("newsUrl", newsUrl);
		return (M)this;
	}
	
	/**
	 * 跳转URL
	 */
	public java.lang.String getNewsUrl() {
		return getStr("newsUrl");
	}

	/**
	 * normal:正常  disable:禁止
	 */
	public M setNewsStatus(java.lang.String newsStatus) {
		set("newsStatus", newsStatus);
		return (M)this;
	}
	
	/**
	 * normal:正常  disable:禁止
	 */
	public java.lang.String getNewsStatus() {
		return getStr("newsStatus");
	}

}
