package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseVAppMenu<M extends BaseVAppMenu<M>> extends Model<M> implements IBean {

	public M setId(Long id) {
		set("id", id);
		return (M)this;
	}

	public Long getId() {
		return getLong("id");
	}

	/**
	 * 功能名
	 */
	public M setFunctionName(String functionName) {
		set("function_name", functionName);
		return (M)this;
	}

	/**
	 * 功能名
	 */
	public String getFunctionName() {
		return getStr("function_name");
	}

	/**
	 * 菜单代码
	 */
	public M setMenuCode(String menuCode) {
		set("menu_code", menuCode);
		return (M)this;
	}

	/**
	 * 菜单代码
	 */
	public String getMenuCode() {
		return getStr("menu_code");
	}

	/**
	 * 菜单名
	 */
	public M setMenuName(String menuName) {
		set("menu_name", menuName);
		return (M)this;
	}

	/**
	 * 菜单名
	 */
	public String getMenuName() {
		return getStr("menu_name");
	}

	/**
	 * 菜单地址
	 */
	public M setMenuUrl(String menuUrl) {
		set("menu_url", menuUrl);
		return (M)this;
	}

	/**
	 * 菜单地址
	 */
	public String getMenuUrl() {
		return getStr("menu_url");
	}

	/**
	 * 父id
	 */
	public M setSid(Long sid) {
		set("sid", sid);
		return (M)this;
	}

	/**
	 * 父id
	 */
	public Long getSid() {
		return getLong("sid");
	}

	/**
	 * 是否制定
	 */
	public M setIstop(String istop) {
		set("istop", istop);
		return (M)this;
	}

	/**
	 * 是否制定
	 */
	public String getIstop() {
		return getStr("istop");
	}

	/**
	 * 菜单控件图地址
	 */
	public M setMenuIcon(String menuIcon) {
		set("menu_icon", menuIcon);
		return (M)this;
	}

	/**
	 * 菜单控件图地址
	 */
	public String getMenuIcon() {
		return getStr("menu_icon");
	}

	/**
	 * 菜单关联
	 */
	public M setRelationNo(String relationNo) {
		set("relation_no", relationNo);
		return (M)this;
	}

	/**
	 * 菜单关联
	 */
	public String getRelationNo() {
		return getStr("relation_no");
	}

	/**
	 * 菜单状态
	 */
	public M setSstatus(String sstatus) {
		set("sstatus", sstatus);
		return (M)this;
	}

	/**
	 * 菜单状态
	 */
	public String getSstatus() {
		return getStr("sstatus");
	}

	/**
	 * 拓展字段1
	 */
	public M setExt1(String ext1) {
		set("ext1", ext1);
		return (M)this;
	}

	/**
	 * 拓展字段1
	 */
	public String getExt1() {
		return getStr("ext1");
	}

	/**
	 * 拓展字段2
	 */
	public M setExt2(String ext2) {
		set("ext2", ext2);
		return (M)this;
	}

	/**
	 * 拓展字段2
	 */
	public String getExt2() {
		return getStr("ext2");
	}

	/**
	 * 拓展字段3
	 */
	public M setExt3(String ext3) {
		set("ext3", ext3);
		return (M)this;
	}

	/**
	 * 拓展字段3
	 */
	public String getExt3() {
		return getStr("ext3");
	}

}
