package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseVDictionaries<M extends BaseVDictionaries<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setDictionariesName(java.lang.String dictionariesName) {
		set("dictionaries_name", dictionariesName);
		return (M)this;
	}
	
	public java.lang.String getDictionariesName() {
		return getStr("dictionaries_name");
	}

	public M setDictionariesKey(java.lang.String dictionariesKey) {
		set("dictionaries_key", dictionariesKey);
		return (M)this;
	}
	
	public java.lang.String getDictionariesKey() {
		return getStr("dictionaries_key");
	}

	public M setDictionariesValue(java.lang.String dictionariesValue) {
		set("dictionaries_value", dictionariesValue);
		return (M)this;
	}
	
	public java.lang.String getDictionariesValue() {
		return getStr("dictionaries_value");
	}

	public M setExtra1(java.lang.String extra1) {
		set("extra1", extra1);
		return (M)this;
	}
	
	public java.lang.String getExtra1() {
		return getStr("extra1");
	}

	public M setExtra2(java.lang.String extra2) {
		set("extra2", extra2);
		return (M)this;
	}
	
	public java.lang.String getExtra2() {
		return getStr("extra2");
	}

	public M setExtra3(java.lang.String extra3) {
		set("extra3", extra3);
		return (M)this;
	}
	
	public java.lang.String getExtra3() {
		return getStr("extra3");
	}

}
