package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseVAppUserAccount<M extends BaseVAppUserAccount<M>> extends Model<M> implements IBean {

	/**
	 * app用户账户表
	 */
	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * app用户账户表
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 用户
	 */
	public M setUserId(java.lang.Long userId) {
		set("userId", userId);
		return (M)this;
	}
	
	/**
	 * 用户
	 */
	public java.lang.Long getUserId() {
		return getLong("userId");
	}

	/**
	 * 系统密码 密文
	 */
	public M setSysPwd(java.lang.String sysPwd) {
		set("sysPwd", sysPwd);
		return (M)this;
	}
	
	/**
	 * 系统密码 密文
	 */
	public java.lang.String getSysPwd() {
		return getStr("sysPwd");
	}

	/**
	 * 账户交易密码 密文
	 */
	public M setPayPwd(java.lang.String payPwd) {
		set("payPwd", payPwd);
		return (M)this;
	}
	
	/**
	 * 账户交易密码 密文
	 */
	public java.lang.String getPayPwd() {
		return getStr("payPwd");
	}

	/**
	 * 状态 normal:正常 freeze:冻结 del:删除
	 */
	public M setCstatus(java.lang.String cstatus) {
		set("cstatus", cstatus);
		return (M)this;
	}
	
	/**
	 * 状态 normal:正常 freeze:冻结 del:删除
	 */
	public java.lang.String getCstatus() {
		return getStr("cstatus");
	}

	/**
	 * 手势密码
	 */
	public M setGesturePwd(java.lang.String gesturePwd) {
		set("gesturePwd", gesturePwd);
		return (M)this;
	}
	
	/**
	 * 手势密码
	 */
	public java.lang.String getGesturePwd() {
		return getStr("gesturePwd");
	}

	/**
	 * 原因
	 */
	public M setHandleCause(java.lang.String handleCause) {
		set("handleCause", handleCause);
		return (M)this;
	}
	
	/**
	 * 原因
	 */
	public java.lang.String getHandleCause() {
		return getStr("handleCause");
	}

	/**
	 * 操作时间
	 */
	public M setHandleTime(java.lang.String handleTime) {
		set("handleTime", handleTime);
		return (M)this;
	}
	
	/**
	 * 操作时间
	 */
	public java.lang.String getHandleTime() {
		return getStr("handleTime");
	}

	/**
	 * 操作人Id
	 */
	public M setOperId(java.lang.Long operId) {
		set("operId", operId);
		return (M)this;
	}
	
	/**
	 * 操作人Id
	 */
	public java.lang.Long getOperId() {
		return getLong("operId");
	}

}
