package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseVAppUser<M extends BaseVAppUser<M>> extends Model<M> implements IBean {

	/**
	 * 用户表
	 */
	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 用户表
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 所属机构
	 */
	public M setOrgId(java.lang.Long orgId) {
		set("orgId", orgId);
		return (M)this;
	}
	
	/**
	 * 所属机构
	 */
	public java.lang.Long getOrgId() {
		return getLong("orgId");
	}

	/**
	 * 机构关联 方便查看无限下级
	 */
	public M setRelationNo(java.lang.String relationNo) {
		set("relationNo", relationNo);
		return (M)this;
	}
	
	/**
	 * 机构关联 方便查看无限下级
	 */
	public java.lang.String getRelationNo() {
		return getStr("relationNo");
	}

	/**
	 * 真实姓名
	 */
	public M setRealName(java.lang.String realName) {
		set("realName", realName);
		return (M)this;
	}
	
	/**
	 * 真实姓名
	 */
	public java.lang.String getRealName() {
		return getStr("realName");
	}

	/**
	 * 昵称
	 */
	public M setNiceName(java.lang.String niceName) {
		set("niceName", niceName);
		return (M)this;
	}
	
	/**
	 * 昵称
	 */
	public java.lang.String getNiceName() {
		return getStr("niceName");
	}

	/**
	 * 登录账号
	 */
	public M setLoginName(java.lang.String loginName) {
		set("loginName", loginName);
		return (M)this;
	}
	
	/**
	 * 登录账号
	 */
	public java.lang.String getLoginName() {
		return getStr("loginName");
	}

	/**
	 * 证件类型 默认就是身份证 01
	 */
	public M setIdType(java.lang.String idType) {
		set("idType", idType);
		return (M)this;
	}
	
	/**
	 * 证件类型 默认就是身份证 01
	 */
	public java.lang.String getIdType() {
		return getStr("idType");
	}

	/**
	 * 证件号 用密钥加密，取出来再解密
	 */
	public M setIdNO(java.lang.String idNO) {
		set("idNO", idNO);
		return (M)this;
	}
	
	/**
	 * 证件号 用密钥加密，取出来再解密
	 */
	public java.lang.String getIdNO() {
		return getStr("idNO");
	}

	/**
	 * 联系手机号
	 */
	public M setPhone(java.lang.String phone) {
		set("phone", phone);
		return (M)this;
	}
	
	/**
	 * 联系手机号
	 */
	public java.lang.String getPhone() {
		return getStr("phone");
	}

	/**
	 * 建立日期 yyyy-MM-dd
	 */
	public M setCreateDate(java.lang.String createDate) {
		set("createDate", createDate);
		return (M)this;
	}
	
	/**
	 * 建立日期 yyyy-MM-dd
	 */
	public java.lang.String getCreateDate() {
		return getStr("createDate");
	}

	/**
	 * 建立时间 HH:mm:ss
	 */
	public M setCreateTime(java.lang.String createTime) {
		set("createTime", createTime);
		return (M)this;
	}
	
	/**
	 * 建立时间 HH:mm:ss
	 */
	public java.lang.String getCreateTime() {
		return getStr("createTime");
	}

	/**
	 * 省
	 */
	public M setProvince(java.lang.String province) {
		set("province", province);
		return (M)this;
	}
	
	/**
	 * 省
	 */
	public java.lang.String getProvince() {
		return getStr("province");
	}

	/**
	 * 市
	 */
	public M setCity(java.lang.String city) {
		set("city", city);
		return (M)this;
	}
	
	/**
	 * 市
	 */
	public java.lang.String getCity() {
		return getStr("city");
	}

	/**
	 * 县
	 */
	public M setArea(java.lang.String area) {
		set("area", area);
		return (M)this;
	}
	
	/**
	 * 县
	 */
	public java.lang.String getArea() {
		return getStr("area");
	}

	/**
	 * 地址
	 */
	public M setAddr(java.lang.String addr) {
		set("addr", addr);
		return (M)this;
	}
	
	/**
	 * 地址
	 */
	public java.lang.String getAddr() {
		return getStr("addr");
	}

	/**
	 * 是否实名 F:未实名 T：实名;N:审核中
	 */
	public M setIsAuth(java.lang.String isAuth) {
		set("isAuth", isAuth);
		return (M)this;
	}
	
	/**
	 * 是否实名 F:未实名 T：实名;N:审核中
	 */
	public java.lang.String getIsAuth() {
		return getStr("isAuth");
	}

	/**
	 * 实名日期 yyyy-MM-dd
	 */
	public M setAuthDate(java.lang.String authDate) {
		set("authDate", authDate);
		return (M)this;
	}
	
	/**
	 * 实名日期 yyyy-MM-dd
	 */
	public java.lang.String getAuthDate() {
		return getStr("authDate");
	}

	/**
	 * 实名时间 HH:mm:ss
	 */
	public M setAuthTime(java.lang.String authTime) {
		set("authTime", authTime);
		return (M)this;
	}
	
	/**
	 * 实名时间 HH:mm:ss
	 */
	public java.lang.String getAuthTime() {
		return getStr("authTime");
	}

	/**
	 * 证件正面照
	 */
	public M setIdFrontImgUrl(java.lang.String idFrontImgUrl) {
		set("idFrontImgUrl", idFrontImgUrl);
		return (M)this;
	}
	
	/**
	 * 证件正面照
	 */
	public java.lang.String getIdFrontImgUrl() {
		return getStr("idFrontImgUrl");
	}

	/**
	 * 证件反面照
	 */
	public M setIdOppositeImgUrl(java.lang.String idOppositeImgUrl) {
		set("idOppositeImgUrl", idOppositeImgUrl);
		return (M)this;
	}
	
	/**
	 * 证件反面照
	 */
	public java.lang.String getIdOppositeImgUrl() {
		return getStr("idOppositeImgUrl");
	}

	/**
	 * 手持证件照
	 */
	public M setIdHandleImgUrl(java.lang.String idHandleImgUrl) {
		set("idHandleImgUrl", idHandleImgUrl);
		return (M)this;
	}
	
	/**
	 * 手持证件照
	 */
	public java.lang.String getIdHandleImgUrl() {
		return getStr("idHandleImgUrl");
	}

	/**
	 * 银行卡正面照
	 */
	public M setBankCardImgUrl(java.lang.String bankCardImgUrl) {
		set("bankCardImgUrl", bankCardImgUrl);
		return (M)this;
	}
	
	/**
	 * 银行卡正面照
	 */
	public java.lang.String getBankCardImgUrl() {
		return getStr("bankCardImgUrl");
	}

	/**
	 * 头像照片位置
	 */
	public M setHeadImgUrl(java.lang.String headImgUrl) {
		set("headImgUrl", headImgUrl);
		return (M)this;
	}
	
	/**
	 * 头像照片位置
	 */
	public java.lang.String getHeadImgUrl() {
		return getStr("headImgUrl");
	}

	/**
	 * token
	 */
	public M setToken(java.lang.String token) {
		set("token", token);
		return (M)this;
	}
	
	/**
	 * token
	 */
	public java.lang.String getToken() {
		return getStr("token");
	}

	/**
	 * 是否设置支付密码 T：设置 F：未设置
	 */
	public M setIsSetTransPwd(java.lang.String isSetTransPwd) {
		set("isSetTransPwd", isSetTransPwd);
		return (M)this;
	}
	
	/**
	 * 是否设置支付密码 T：设置 F：未设置
	 */
	public java.lang.String getIsSetTransPwd() {
		return getStr("isSetTransPwd");
	}

	/**
	 * 二维码存放地址
	 */
	public M setQrcodeUrl(java.lang.String qrcodeUrl) {
		set("qrcodeUrl", qrcodeUrl);
		return (M)this;
	}
	
	/**
	 * 二维码存放地址
	 */
	public java.lang.String getQrcodeUrl() {
		return getStr("qrcodeUrl");
	}

	/**
	 * 公司id
	 */
	public M setCompanyId(java.lang.Long companyId) {
		set("companyId", companyId);
		return (M)this;
	}
	
	/**
	 * 公司id
	 */
	public java.lang.Long getCompanyId() {
		return getLong("companyId");
	}

	/**
	 * staff:普通员工,manage:管理员,front:前台
	 */
	public M setRole(java.lang.String role) {
		set("role", role);
		return (M)this;
	}
	
	/**
	 * staff:普通员工,manage:管理员,front:前台
	 */
	public java.lang.String getRole() {
		return getStr("role");
	}

	/**
	 * 密钥 用于加解密身份证号、卡号
	 */
	public M setWorkKey(java.lang.String workKey) {
		set("workKey", workKey);
		return (M)this;
	}
	
	/**
	 * 密钥 用于加解密身份证号、卡号
	 */
	public java.lang.String getWorkKey() {
		return getStr("workKey");
	}

	/**
	 * 审核失败原因
	 */
	public M setFailReason(java.lang.String failReason) {
		set("failReason", failReason);
		return (M)this;
	}
	
	/**
	 * 审核失败原因
	 */
	public java.lang.String getFailReason() {
		return getStr("failReason");
	}

	/**
	 * 用户唯一标识码
	 */
	public M setSoleCode(java.lang.String soleCode) {
		set("soleCode", soleCode);
		return (M)this;
	}
	
	/**
	 * 用户唯一标识码
	 */
	public java.lang.String getSoleCode() {
		return getStr("soleCode");
	}

	/**
	 * 有效期
	 */
	public M setValidityDate(java.lang.String validityDate) {
		set("validityDate", validityDate);
		return (M)this;
	}
	
	/**
	 * 有效期
	 */
	public java.lang.String getValidityDate() {
		return getStr("validityDate");
	}

	/**
	 * 性别
	 */
	public M setSex(java.lang.String sex) {
		set("sex", sex);
		return (M)this;
	}
	
	/**
	 * 性别
	 */
	public java.lang.String getSex() {
		return getStr("sex");
	}

	/**
	 * 友盟设备号
	 */
	public M setDeviceToken(java.lang.String deviceToken) {
		set("deviceToken", deviceToken);
		return (M)this;
	}
	
	/**
	 * 友盟设备号
	 */
	public java.lang.String getDeviceToken() {
		return getStr("deviceToken");
	}

	/**
	 * 1--ios 2--andriod
	 */
	public M setDeviceType(java.lang.String deviceType) {
		set("deviceType", deviceType);
		return (M)this;
	}
	
	/**
	 * 1--ios 2--andriod
	 */
	public java.lang.String getDeviceType() {
		return getStr("deviceType");
	}

	/**
	 * T---在线  F--离线
	 */
	public M setIsOnlineApp(java.lang.String isOnlineApp) {
		set("isOnlineApp", isOnlineApp);
		return (M)this;
	}
	
	/**
	 * T---在线  F--离线
	 */
	public java.lang.String getIsOnlineApp() {
		return getStr("isOnlineApp");
	}

	/**
	 * 微信openid，关注公众号并使用公众号登入后产生

	 */
	public M setWxOpenId(java.lang.String wxOpenId) {
		set("wx_open_id", wxOpenId);
		return (M)this;
	}
	
	/**
	 * 微信openid，关注公众号并使用公众号登入后产生

	 */
	public java.lang.String getWxOpenId() {
		return getStr("wx_open_id");
	}

	/**
	 * 扩展字段1
	 */
	public M setExp1(java.lang.String exp1) {
		set("exp1", exp1);
		return (M)this;
	}
	
	/**
	 * 扩展字段1
	 */
	public java.lang.String getExp1() {
		return getStr("exp1");
	}

	/**
	 * 扩展字段2
	 */
	public M setExp2(java.lang.String exp2) {
		set("exp2", exp2);
		return (M)this;
	}
	
	/**
	 * 扩展字段2
	 */
	public java.lang.String getExp2() {
		return getStr("exp2");
	}

}
