package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseVCompany<M extends BaseVCompany<M>> extends Model<M> implements IBean {

	/**
	 * 公司管理
	 */
	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 公司管理
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 公司编码
	 */
	public M setCompanyCode(java.lang.String companyCode) {
		set("companyCode", companyCode);
		return (M)this;
	}
	
	/**
	 * 公司编码
	 */
	public java.lang.String getCompanyCode() {
		return getStr("companyCode");
	}

	/**
	 * 公司名
	 */
	public M setCompanyName(java.lang.String companyName) {
		set("companyName", companyName);
		return (M)this;
	}
	
	/**
	 * 公司名
	 */
	public java.lang.String getCompanyName() {
		return getStr("companyName");
	}

	/**
	 * 创建日期yyyy-mm-dd
	 */
	public M setCreateDate(java.lang.String createDate) {
		set("createDate", createDate);
		return (M)this;
	}
	
	/**
	 * 创建日期yyyy-mm-dd
	 */
	public java.lang.String getCreateDate() {
		return getStr("createDate");
	}

	/**
	 * 联系人手机号
	 */
	public M setPhone(java.lang.String phone) {
		set("phone", phone);
		return (M)this;
	}
	
	/**
	 * 联系人手机号
	 */
	public java.lang.String getPhone() {
		return getStr("phone");
	}

	/**
	 * 联系人
	 */
	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	/**
	 * 联系人
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 审核类型:(manage:管理员审核,front:前台审核,staff:员工自己审核)
	 */
	public M setApplyType(java.lang.String applyType) {
		set("applyType", applyType);
		return (M)this;
	}
	
	/**
	 * 审核类型:(manage:管理员审核,front:前台审核,staff:员工自己审核)
	 */
	public java.lang.String getApplyType() {
		return getStr("applyType");
	}

	/**
	 * 法人身份证
	 */
	public M setCorporationID(java.lang.String corporationID) {
		set("corporationID", corporationID);
		return (M)this;
	}
	
	/**
	 * 法人身份证
	 */
	public java.lang.String getCorporationID() {
		return getStr("corporationID");
	}

	/**
	 * 营业执照号
	 */
	public M setLicenceNo(java.lang.String licenceNo) {
		set("licenceNo", licenceNo);
		return (M)this;
	}
	
	/**
	 * 营业执照号
	 */
	public java.lang.String getLicenceNo() {
		return getStr("licenceNo");
	}

	/**
	 * 公司地址
	 */
	public M setAddr(java.lang.String addr) {
		set("addr", addr);
		return (M)this;
	}
	
	/**
	 * 公司地址
	 */
	public java.lang.String getAddr() {
		return getStr("addr");
	}

	/**
	 * 大楼id
	 */
	public M setOrgId(java.lang.Long orgId) {
		set("orgId", orgId);
		return (M)this;
	}
	
	/**
	 * 大楼id
	 */
	public java.lang.Long getOrgId() {
		return getLong("orgId");
	}

	/**
	 * 公司所在楼层
	 */
	public M setCompanyFloor(java.lang.String companyFloor) {
		set("companyFloor", companyFloor);
		return (M)this;
	}
	
	/**
	 * 公司所在楼层
	 */
	public java.lang.String getCompanyFloor() {
		return getStr("companyFloor");
	}

	/**
	 * 是否邀约0否1是
	 */
	public M setIsyaoyue(java.lang.String isyaoyue) {
		set("isyaoyue", isyaoyue);
		return (M)this;
	}
	
	/**
	 * 是否邀约0否1是
	 */
	public java.lang.String getIsyaoyue() {
		return getStr("isyaoyue");
	}

	/**
	 * 扩展字段
	 */
	public M setExt1(java.lang.String ext1) {
		set("ext1", ext1);
		return (M)this;
	}
	
	/**
	 * 扩展字段
	 */
	public java.lang.String getExt1() {
		return getStr("ext1");
	}

	/**
	 * 扩展字段
	 */
	public M setExt2(java.lang.String ext2) {
		set("ext2", ext2);
		return (M)this;
	}
	
	/**
	 * 扩展字段
	 */
	public java.lang.String getExt2() {
		return getStr("ext2");
	}

}
