package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseActHiActinst<M extends BaseActHiActinst<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("ID_", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("ID_");
	}

	public M setProcDefId(java.lang.String procDefId) {
		set("PROC_DEF_ID_", procDefId);
		return (M)this;
	}
	
	public java.lang.String getProcDefId() {
		return getStr("PROC_DEF_ID_");
	}

	public M setProcInstId(java.lang.String procInstId) {
		set("PROC_INST_ID_", procInstId);
		return (M)this;
	}
	
	public java.lang.String getProcInstId() {
		return getStr("PROC_INST_ID_");
	}

	public M setExecutionId(java.lang.String executionId) {
		set("EXECUTION_ID_", executionId);
		return (M)this;
	}
	
	public java.lang.String getExecutionId() {
		return getStr("EXECUTION_ID_");
	}

	public M setActId(java.lang.String actId) {
		set("ACT_ID_", actId);
		return (M)this;
	}
	
	public java.lang.String getActId() {
		return getStr("ACT_ID_");
	}

	public M setTaskId(java.lang.String taskId) {
		set("TASK_ID_", taskId);
		return (M)this;
	}
	
	public java.lang.String getTaskId() {
		return getStr("TASK_ID_");
	}

	public M setCallProcInstId(java.lang.String callProcInstId) {
		set("CALL_PROC_INST_ID_", callProcInstId);
		return (M)this;
	}
	
	public java.lang.String getCallProcInstId() {
		return getStr("CALL_PROC_INST_ID_");
	}

	public M setActName(java.lang.String actName) {
		set("ACT_NAME_", actName);
		return (M)this;
	}
	
	public java.lang.String getActName() {
		return getStr("ACT_NAME_");
	}

	public M setActType(java.lang.String actType) {
		set("ACT_TYPE_", actType);
		return (M)this;
	}
	
	public java.lang.String getActType() {
		return getStr("ACT_TYPE_");
	}

	public M setAssignee(java.lang.String assignee) {
		set("ASSIGNEE_", assignee);
		return (M)this;
	}
	
	public java.lang.String getAssignee() {
		return getStr("ASSIGNEE_");
	}

	public M setStartTime(java.util.Date startTime) {
		set("START_TIME_", startTime);
		return (M)this;
	}
	
	public java.util.Date getStartTime() {
		return get("START_TIME_");
	}

	public M setEndTime(java.util.Date endTime) {
		set("END_TIME_", endTime);
		return (M)this;
	}
	
	public java.util.Date getEndTime() {
		return get("END_TIME_");
	}

	public M setDuration(java.lang.Long duration) {
		set("DURATION_", duration);
		return (M)this;
	}
	
	public java.lang.Long getDuration() {
		return getLong("DURATION_");
	}

	public M setTenantId(java.lang.String tenantId) {
		set("TENANT_ID_", tenantId);
		return (M)this;
	}
	
	public java.lang.String getTenantId() {
		return getStr("TENANT_ID_");
	}

}
