package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseVSysUser<M extends BaseVSysUser<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setParentId(java.math.BigInteger parentId) {
		set("parent_id", parentId);
		return (M)this;
	}
	
	public java.math.BigInteger getParentId() {
		return get("parent_id");
	}

	/**
	 * 登录名
	 */
	public M setUsername(java.lang.String username) {
		set("username", username);
		return (M)this;
	}
	
	/**
	 * 登录名
	 */
	public java.lang.String getUsername() {
		return getStr("username");
	}

	/**
	 * 登录密码
	 */
	public M setPassword(java.lang.String password) {
		set("password", password);
		return (M)this;
	}
	
	/**
	 * 登录密码
	 */
	public java.lang.String getPassword() {
		return getStr("password");
	}

	/**
	 * 真实姓名
	 */
	public M setTrueName(java.lang.String trueName) {
		set("true_name", trueName);
		return (M)this;
	}
	
	/**
	 * 真实姓名
	 */
	public java.lang.String getTrueName() {
		return getStr("true_name");
	}

	/**
	 * 电话
	 */
	public M setTel(java.lang.String tel) {
		set("tel", tel);
		return (M)this;
	}
	
	/**
	 * 电话
	 */
	public java.lang.String getTel() {
		return getStr("tel");
	}

	/**
	 * 是否删除
	 */
	public M setIsDel(java.lang.String isDel) {
		set("is_del", isDel);
		return (M)this;
	}
	
	/**
	 * 是否删除
	 */
	public java.lang.String getIsDel() {
		return getStr("is_del");
	}

	/**
	 * 创建时间
	 */
	public M setCreatetime(java.lang.String createtime) {
		set("createtime", createtime);
		return (M)this;
	}
	
	/**
	 * 创建时间
	 */
	public java.lang.String getCreatetime() {
		return getStr("createtime");
	}

	/**
	 * 登入时间
	 */
	public M setLogintime(java.lang.String logintime) {
		set("logintime", logintime);
		return (M)this;
	}
	
	/**
	 * 登入时间
	 */
	public java.lang.String getLogintime() {
		return getStr("logintime");
	}

	public M setExtra1(java.lang.String extra1) {
		set("extra1", extra1);
		return (M)this;
	}
	
	public java.lang.String getExtra1() {
		return getStr("extra1");
	}

	public M setExtra2(java.lang.String extra2) {
		set("extra2", extra2);
		return (M)this;
	}
	
	public java.lang.String getExtra2() {
		return getStr("extra2");
	}

	public M setExtra3(java.lang.String extra3) {
		set("extra3", extra3);
		return (M)this;
	}
	
	public java.lang.String getExtra3() {
		return getStr("extra3");
	}

	public M setRoleId(java.lang.Long roleId) {
		set("role_id", roleId);
		return (M)this;
	}
	
	public java.lang.Long getRoleId() {
		return getLong("role_id");
	}

	public M setToken(java.lang.String token) {
		set("token", token);
		return (M)this;
	}
	
	public java.lang.String getToken() {
		return getStr("token");
	}

	/**
	 * 是否已经同步 同步：T，未同步 :F
	 */
	public M setIsSync(java.lang.String isSync) {
		set("isSync", isSync);
		return (M)this;
	}
	
	/**
	 * 是否已经同步 同步：T，未同步 :F
	 */
	public java.lang.String getIsSync() {
		return getStr("isSync");
	}

}
