package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseActGeBytearray<M extends BaseActGeBytearray<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("ID_", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("ID_");
	}

	public M setRev(java.lang.Integer rev) {
		set("REV_", rev);
		return (M)this;
	}
	
	public java.lang.Integer getRev() {
		return getInt("REV_");
	}

	public M setName(java.lang.String name) {
		set("NAME_", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("NAME_");
	}

	public M setDeploymentId(java.lang.String deploymentId) {
		set("DEPLOYMENT_ID_", deploymentId);
		return (M)this;
	}
	
	public java.lang.String getDeploymentId() {
		return getStr("DEPLOYMENT_ID_");
	}

	public M setBytes(byte[] bytes) {
		set("BYTES_", bytes);
		return (M)this;
	}
	
	public byte[] getBytes() {
		return get("BYTES_");
	}

	public M setGenerated(java.lang.Integer generated) {
		set("GENERATED_", generated);
		return (M)this;
	}
	
	public java.lang.Integer getGenerated() {
		return getInt("GENERATED_");
	}

}
