package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseVAccessConfig<M extends BaseVAccessConfig<M>> extends Model<M> implements IBean {

	public M setId(Long id) {
		set("id", id);
		return (M)this;
	}

	public Long getId() {
		return getLong("id");
	}

	/**
	 * 通行方式(QRCODE:FACE)
	 */
	public M setPassMethod(String passMethod) {
		set("pass_method", passMethod);
		return (M)this;
	}

	/**
	 * 通行方式(QRCODE:FACE)
	 */
	public String getPassMethod() {
		return getStr("pass_method");
	}

	/**
	 * 产品id
	 */
	public M setProductId(Long productId) {
		set("product_id", productId);
		return (M)this;
	}

	/**
	 * 产品id
	 */
	public Long getProductId() {
		return getLong("product_id");
	}

	/**
	 * 创建时间
	 */
	public M setCreatetime(String createtime) {
		set("createtime", createtime);
		return (M)this;
	}

	/**
	 * 创建时间
	 */
	public String getCreatetime() {
		return getStr("createtime");
	}

	public M setExtra1(String extra1) {
		set("extra1", extra1);
		return (M)this;
	}

	public String getExtra1() {
		return getStr("extra1");
	}

	public M setExtra2(String extra2) {
		set("extra2", extra2);
		return (M)this;
	}

	public String getExtra2() {
		return getStr("extra2");
	}

	public M setExtra3(String extra3) {
		set("extra3", extra3);
		return (M)this;
	}

	public String getExtra3() {
		return getStr("extra3");
	}

}
