package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseVUserPost<M extends BaseVUserPost<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setUserId(java.lang.Long userId) {
		set("userId", userId);
		return (M)this;
	}
	
	public java.lang.Long getUserId() {
		return getLong("userId");
	}

	/**
	 * ??λ???? 1????Լ?ڣ?2?????????
	 */
	public M setPostId(java.lang.Long postId) {
		set("postId", postId);
		return (M)this;
	}
	
	/**
	 * ??λ???? 1????Լ?ڣ?2?????????
	 */
	public java.lang.Long getPostId() {
		return getLong("postId");
	}

}
