package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseVAppCheckindate<M extends BaseVAppCheckindate<M>> extends Model<M> implements IBean {

	/**
	 * 考勤打卡
	 */
	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 考勤打卡
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 规则id
	 */
	public M setGroupId(java.lang.Long groupId) {
		set("group_id", groupId);
		return (M)this;
	}
	
	/**
	 * 规则id
	 */
	public java.lang.Long getGroupId() {
		return getLong("group_id");
	}

	/**
	 * 工作日。若为固定时间上下班或自由上下班，则1到6分别表示星期一到星期六，0表示星期日；若为按班次上下班，则表示拉取班次的日期。
	 */
	public M setWorkdays(java.lang.String workdays) {
		set("workdays", workdays);
		return (M)this;
	}
	
	/**
	 * 工作日。若为固定时间上下班或自由上下班，则1到6分别表示星期一到星期六，0表示星期日；若为按班次上下班，则表示拉取班次的日期。
	 */
	public java.lang.String getWorkdays() {
		return getStr("workdays");
	}

	/**
	 * 弹性时间（毫秒）
	 */
	public M setFlexTime(java.lang.Integer flexTime) {
		set("flex_time", flexTime);
		return (M)this;
	}
	
	/**
	 * 弹性时间（毫秒）
	 */
	public java.lang.Integer getFlexTime() {
		return getInt("flex_time");
	}

	/**
	 * 下班不需要打卡 T--是  F--否
	 */
	public M setNoneedOffwork(java.lang.String noneedOffwork) {
		set("noneed_offwork", noneedOffwork);
		return (M)this;
	}
	
	/**
	 * 下班不需要打卡 T--是  F--否
	 */
	public java.lang.String getNoneedOffwork() {
		return getStr("noneed_offwork");
	}

	/**
	 * 打卡时间限制（毫秒）
	 */
	public M setLimitAheadtime(java.lang.Integer limitAheadtime) {
		set("limit_aheadtime", limitAheadtime);
		return (M)this;
	}
	
	/**
	 * 打卡时间限制（毫秒）
	 */
	public java.lang.Integer getLimitAheadtime() {
		return getInt("limit_aheadtime");
	}

	/**
	 * 扩展字段1
	 */
	public M setExp1(java.lang.String exp1) {
		set("exp1", exp1);
		return (M)this;
	}
	
	/**
	 * 扩展字段1
	 */
	public java.lang.String getExp1() {
		return getStr("exp1");
	}

	/**
	 * 扩展字段2
	 */
	public M setExp2(java.lang.String exp2) {
		set("exp2", exp2);
		return (M)this;
	}
	
	/**
	 * 扩展字段2
	 */
	public java.lang.String getExp2() {
		return getStr("exp2");
	}

}
