package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseActReProcdef<M extends BaseActReProcdef<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("ID_", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("ID_");
	}

	public M setRev(java.lang.Integer rev) {
		set("REV_", rev);
		return (M)this;
	}
	
	public java.lang.Integer getRev() {
		return getInt("REV_");
	}

	public M setCategory(java.lang.String category) {
		set("CATEGORY_", category);
		return (M)this;
	}
	
	public java.lang.String getCategory() {
		return getStr("CATEGORY_");
	}

	public M setName(java.lang.String name) {
		set("NAME_", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("NAME_");
	}

	public M setKey(java.lang.String key) {
		set("KEY_", key);
		return (M)this;
	}
	
	public java.lang.String getKey() {
		return getStr("KEY_");
	}

	public M setVersion(java.lang.Integer version) {
		set("VERSION_", version);
		return (M)this;
	}
	
	public java.lang.Integer getVersion() {
		return getInt("VERSION_");
	}

	public M setDeploymentId(java.lang.String deploymentId) {
		set("DEPLOYMENT_ID_", deploymentId);
		return (M)this;
	}
	
	public java.lang.String getDeploymentId() {
		return getStr("DEPLOYMENT_ID_");
	}

	public M setResourceName(java.lang.String resourceName) {
		set("RESOURCE_NAME_", resourceName);
		return (M)this;
	}
	
	public java.lang.String getResourceName() {
		return getStr("RESOURCE_NAME_");
	}

	public M setDgrmResourceName(java.lang.String dgrmResourceName) {
		set("DGRM_RESOURCE_NAME_", dgrmResourceName);
		return (M)this;
	}
	
	public java.lang.String getDgrmResourceName() {
		return getStr("DGRM_RESOURCE_NAME_");
	}

	public M setDescription(java.lang.String description) {
		set("DESCRIPTION_", description);
		return (M)this;
	}
	
	public java.lang.String getDescription() {
		return getStr("DESCRIPTION_");
	}

	public M setHasStartFormKey(java.lang.Integer hasStartFormKey) {
		set("HAS_START_FORM_KEY_", hasStartFormKey);
		return (M)this;
	}
	
	public java.lang.Integer getHasStartFormKey() {
		return getInt("HAS_START_FORM_KEY_");
	}

	public M setHasGraphicalNotation(java.lang.Integer hasGraphicalNotation) {
		set("HAS_GRAPHICAL_NOTATION_", hasGraphicalNotation);
		return (M)this;
	}
	
	public java.lang.Integer getHasGraphicalNotation() {
		return getInt("HAS_GRAPHICAL_NOTATION_");
	}

	public M setSuspensionState(java.lang.Integer suspensionState) {
		set("SUSPENSION_STATE_", suspensionState);
		return (M)this;
	}
	
	public java.lang.Integer getSuspensionState() {
		return getInt("SUSPENSION_STATE_");
	}

	public M setTenantId(java.lang.String tenantId) {
		set("TENANT_ID_", tenantId);
		return (M)this;
	}
	
	public java.lang.String getTenantId() {
		return getStr("TENANT_ID_");
	}

}
