package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseActHiAttachment<M extends BaseActHiAttachment<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("ID_", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("ID_");
	}

	public M setRev(java.lang.Integer rev) {
		set("REV_", rev);
		return (M)this;
	}
	
	public java.lang.Integer getRev() {
		return getInt("REV_");
	}

	public M setUserId(java.lang.String userId) {
		set("USER_ID_", userId);
		return (M)this;
	}
	
	public java.lang.String getUserId() {
		return getStr("USER_ID_");
	}

	public M setName(java.lang.String name) {
		set("NAME_", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("NAME_");
	}

	public M setDescription(java.lang.String description) {
		set("DESCRIPTION_", description);
		return (M)this;
	}
	
	public java.lang.String getDescription() {
		return getStr("DESCRIPTION_");
	}

	public M setType(java.lang.String type) {
		set("TYPE_", type);
		return (M)this;
	}
	
	public java.lang.String getType() {
		return getStr("TYPE_");
	}

	public M setTaskId(java.lang.String taskId) {
		set("TASK_ID_", taskId);
		return (M)this;
	}
	
	public java.lang.String getTaskId() {
		return getStr("TASK_ID_");
	}

	public M setProcInstId(java.lang.String procInstId) {
		set("PROC_INST_ID_", procInstId);
		return (M)this;
	}
	
	public java.lang.String getProcInstId() {
		return getStr("PROC_INST_ID_");
	}

	public M setUrl(java.lang.String url) {
		set("URL_", url);
		return (M)this;
	}
	
	public java.lang.String getUrl() {
		return getStr("URL_");
	}

	public M setContentId(java.lang.String contentId) {
		set("CONTENT_ID_", contentId);
		return (M)this;
	}
	
	public java.lang.String getContentId() {
		return getStr("CONTENT_ID_");
	}

	public M setTime(java.util.Date time) {
		set("TIME_", time);
		return (M)this;
	}
	
	public java.util.Date getTime() {
		return get("TIME_");
	}

}
