package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseVPosp<M extends BaseVPosp<M>> extends Model<M> implements IBean {

	/**
	 * 上位机
	 */
	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 上位机
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 大楼ID
	 */
	public M setOrgId(java.lang.Long orgId) {
		set("orgId", orgId);
		return (M)this;
	}
	
	/**
	 * 大楼ID
	 */
	public java.lang.Long getOrgId() {
		return getLong("orgId");
	}

	/**
	 * 上位机编码
	 */
	public M setPospCode(java.lang.String pospCode) {
		set("pospCode", pospCode);
		return (M)this;
	}
	
	/**
	 * 上位机编码
	 */
	public java.lang.String getPospCode() {
		return getStr("pospCode");
	}

	/**
	 * 上位机名称
	 */
	public M setPospName(java.lang.String pospName) {
		set("pospName", pospName);
		return (M)this;
	}
	
	/**
	 * 上位机名称
	 */
	public java.lang.String getPospName() {
		return getStr("pospName");
	}

	/**
	 * normal:正常  disable:禁止
	 */
	public M setCstatus(java.lang.String cstatus) {
		set("cstatus", cstatus);
		return (M)this;
	}
	
	/**
	 * normal:正常  disable:禁止
	 */
	public java.lang.String getCstatus() {
		return getStr("cstatus");
	}

	/**
	 * 随机字符串
	 */
	public M setRonDomNum(java.lang.String ronDomNum) {
		set("ronDomNum", ronDomNum);
		return (M)this;
	}
	
	/**
	 * 随机字符串
	 */
	public java.lang.String getRonDomNum() {
		return getStr("ronDomNum");
	}

	/**
	 * 密码验证传输-28位秘钥，新增时随机生成，上传数据进行验证
	 */
	public M setPrivateKey(java.lang.String privateKey) {
		set("privateKey", privateKey);
		return (M)this;
	}
	
	/**
	 * 密码验证传输-28位秘钥，新增时随机生成，上传数据进行验证
	 */
	public java.lang.String getPrivateKey() {
		return getStr("privateKey");
	}

}
