package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseVAppUserMessage<M extends BaseVAppUserMessage<M>> extends Model<M> implements IBean {

	public M setId(Long id) {
		set("id", id);
		return (M)this;
	}

	public Long getId() {
		return getLong("id");
	}

	/**
	 * 消息来源
	 */
	public M setFromUserId(Long fromUserId) {
		set("fromUserId", fromUserId);
		return (M)this;
	}

	/**
	 * 消息来源
	 */
	public Long getFromUserId() {
		return getLong("fromUserId");
	}

	/**
	 * 消息去向
	 */
	public M setToUserId(Long toUserId) {
		set("toUserId", toUserId);
		return (M)this;
	}

	/**
	 * 消息去向
	 */
	public Long getToUserId() {
		return getLong("toUserId");
	}

	/**
	 * 内容
	 */
	public M setMessage(String message) {
		set("message", message);
		return (M)this;
	}

	/**
	 * 内容
	 */
	public String getMessage() {
		return getStr("message");
	}

	/**
	 * 上传时间
	 */
	public M setUpdateTime(String updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}

	/**
	 * 上传时间
	 */
	public String getUpdateTime() {
		return getStr("update_time");
	}

	/**
	 * 消息类型
	 */
	public M setType(Integer type) {
		set("type", type);
		return (M)this;
	}

	/**
	 * 消息类型
	 */
	public Integer getType() {
		return getInt("type");
	}

	/**
	 * 扩展字段1
	 */
	public M setExt1(String ext1) {
		set("ext1", ext1);
		return (M)this;
	}

	/**
	 * 扩展字段1
	 */
	public String getExt1() {
		return getStr("ext1");
	}

	/**
	 * 扩展字段2
	 */
	public M setExt2(String ext2) {
		set("ext2", ext2);
		return (M)this;
	}

	/**
	 * 扩展字段2
	 */
	public String getExt2() {
		return getStr("ext2");
	}

	/**
	 * 扩展字段3
	 */
	public M setExt3(String ext3) {
		set("ext3", ext3);
		return (M)this;
	}

	/**
	 * 扩展字段3
	 */
	public String getExt3() {
		return getStr("ext3");
	}

}
