package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseVDInout<M extends BaseVDInout<M>> extends Model<M> implements IBean {

	/**
	 * 上位机进出日志
	 */
	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 上位机进出日志
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 大楼编号
	 */
	public M setOrgCode(java.lang.String orgCode) {
		set("orgCode", orgCode);
		return (M)this;
	}
	
	/**
	 * 大楼编号
	 */
	public java.lang.String getOrgCode() {
		return getStr("orgCode");
	}

	/**
	 * 上位机编号
	 */
	public M setPospCode(java.lang.String pospCode) {
		set("pospCode", pospCode);
		return (M)this;
	}
	
	/**
	 * 上位机编号
	 */
	public java.lang.String getPospCode() {
		return getStr("pospCode");
	}

	/**
	 * 设备扫描日期：yyyy:MM:dd
	 */
	public M setScanDate(java.lang.String scanDate) {
		set("scanDate", scanDate);
		return (M)this;
	}
	
	/**
	 * 设备扫描日期：yyyy:MM:dd
	 */
	public java.lang.String getScanDate() {
		return getStr("scanDate");
	}

	/**
	 * 设备扫描时间：HH:mm:ss
	 */
	public M setScanTime(java.lang.String scanTime) {
		set("scanTime", scanTime);
		return (M)this;
	}
	
	/**
	 * 设备扫描时间：HH:mm:ss
	 */
	public java.lang.String getScanTime() {
		return getStr("scanTime");
	}

	/**
	 * 进出类型：in/out
	 */
	public M setInOrOut(java.lang.String inOrOut) {
		set("inOrOut", inOrOut);
		return (M)this;
	}
	
	/**
	 * 进出类型：in/out
	 */
	public java.lang.String getInOrOut() {
		return getStr("inOrOut");
	}

	/**
	 * 通道编号
	 */
	public M setOutNumber(java.lang.String outNumber) {
		set("outNumber", outNumber);
		return (M)this;
	}
	
	/**
	 * 通道编号
	 */
	public java.lang.String getOutNumber() {
		return getStr("outNumber");
	}

	/**
	 * 通行设备的类型：QRCODE/FACE
	 */
	public M setDeviceType(java.lang.String deviceType) {
		set("deviceType", deviceType);
		return (M)this;
	}
	
	/**
	 * 通行设备的类型：QRCODE/FACE
	 */
	public java.lang.String getDeviceType() {
		return getStr("deviceType");
	}

	/**
	 * 设备的IP地址
	 */
	public M setDeviceIp(java.lang.String deviceIp) {
		set("deviceIp", deviceIp);
		return (M)this;
	}
	
	/**
	 * 设备的IP地址
	 */
	public java.lang.String getDeviceIp() {
		return getStr("deviceIp");
	}

	/**
	 * 通行人员类型：staff/visitor
	 */
	public M setUserType(java.lang.String userType) {
		set("userType", userType);
		return (M)this;
	}
	
	/**
	 * 通行人员类型：staff/visitor
	 */
	public java.lang.String getUserType() {
		return getStr("userType");
	}

	/**
	 * 通行人员名字
	 */
	public M setUserName(java.lang.String userName) {
		set("userName", userName);
		return (M)this;
	}
	
	/**
	 * 通行人员名字
	 */
	public java.lang.String getUserName() {
		return getStr("userName");
	}

	/**
	 * 通行人员证件号
	 */
	public M setIdCard(java.lang.String idCard) {
		set("idCard", idCard);
		return (M)this;
	}
	
	/**
	 * 通行人员证件号
	 */
	public java.lang.String getIdCard() {
		return getStr("idCard");
	}

	/**
	 * 发送记录的标识：已发送(T)/未发送(F)
	 */
	public M setIsSendFlag(java.lang.String isSendFlag) {
		set("isSendFlag", isSendFlag);
		return (M)this;
	}
	
	/**
	 * 发送记录的标识：已发送(T)/未发送(F)
	 */
	public java.lang.String getIsSendFlag() {
		return getStr("isSendFlag");
	}

	/**
	 * 拓展字段1
	 */
	public M setExpt1(java.lang.String expt1) {
		set("expt1", expt1);
		return (M)this;
	}
	
	/**
	 * 拓展字段1
	 */
	public java.lang.String getExpt1() {
		return getStr("expt1");
	}

	/**
	 * 拓展字段2
	 */
	public M setExpt2(java.lang.String expt2) {
		set("expt2", expt2);
		return (M)this;
	}
	
	/**
	 * 拓展字段2
	 */
	public java.lang.String getExpt2() {
		return getStr("expt2");
	}

}
