package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseVSync<M extends BaseVSync<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 类型 visitor 访客记录， staff 员工
	 */
	public M setType(java.lang.String type) {
		set("type", type);
		return (M)this;
	}
	
	/**
	 * 类型 visitor 访客记录， staff 员工
	 */
	public java.lang.String getType() {
		return getStr("type");
	}

	/**
	 * 是否同步
	 */
	public M setIsReceive(java.lang.String isReceive) {
		set("isReceive", isReceive);
		return (M)this;
	}
	
	/**
	 * 是否同步
	 */
	public java.lang.String getIsReceive() {
		return getStr("isReceive");
	}

	/**
	 * 同步数据的ID
	 */
	public M setRelationId(java.lang.Long relationId) {
		set("relationId", relationId);
		return (M)this;
	}
	
	/**
	 * 同步数据的ID
	 */
	public java.lang.Long getRelationId() {
		return getLong("relationId");
	}

	/**
	 * 上位机编号
	 */
	public M setPospCode(java.lang.String pospCode) {
		set("pospCode", pospCode);
		return (M)this;
	}
	
	/**
	 * 上位机编号
	 */
	public java.lang.String getPospCode() {
		return getStr("pospCode");
	}

}
