package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseVAppUser<M extends BaseVAppUser<M>> extends Model<M> implements IBean {

	/**
	 * 实人认证
	 */
	public M setId(Long id) {
		set("id", id);
		return (M)this;
	}

	/**
	 * 实人认证
	 */
	public Long getId() {
		return getLong("id");
	}

	/**
	 * 所属机构
	 */
	public M setOrgId(Long orgId) {
		set("orgId", orgId);
		return (M)this;
	}

	/**
	 * 所属机构
	 */
	public Long getOrgId() {
		return getLong("orgId");
	}

	/**
	 * 机构关联 方便查看无限下级
	 */
	public M setRelationNo(String relationNo) {
		set("relationNo", relationNo);
		return (M)this;
	}

	/**
	 * 机构关联 方便查看无限下级
	 */
	public String getRelationNo() {
		return getStr("relationNo");
	}

	/**
	 * 真实姓名
	 */
	public M setRealName(String realName) {
		set("realName", realName);
		return (M)this;
	}

	/**
	 * 真实姓名
	 */
	public String getRealName() {
		return getStr("realName");
	}

	/**
	 * 昵称
	 */
	public M setNiceName(String niceName) {
		set("niceName", niceName);
		return (M)this;
	}

	/**
	 * 昵称
	 */
	public String getNiceName() {
		return getStr("niceName");
	}

	/**
	 * 登录账号
	 */
	public M setLoginName(String loginName) {
		set("loginName", loginName);
		return (M)this;
	}

	/**
	 * 登录账号
	 */
	public String getLoginName() {
		return getStr("loginName");
	}

	/**
	 * 证件类型 默认就是身份证 01
	 */
	public M setIdType(String idType) {
		set("idType", idType);
		return (M)this;
	}

	/**
	 * 证件类型 默认就是身份证 01
	 */
	public String getIdType() {
		return getStr("idType");
	}

	/**
	 * 证件号 用密钥加密，取出来再解密
	 */
	public M setIdNO(String idNO) {
		set("idNO", idNO);
		return (M)this;
	}

	/**
	 * 证件号 用密钥加密，取出来再解密
	 */
	public String getIdNO() {
		return getStr("idNO");
	}

	/**
	 * 联系手机号
	 */
	public M setPhone(String phone) {
		set("phone", phone);
		return (M)this;
	}

	/**
	 * 联系手机号
	 */
	public String getPhone() {
		return getStr("phone");
	}

	/**
	 * 建立日期 yyyy-MM-dd
	 */
	public M setCreateDate(String createDate) {
		set("createDate", createDate);
		return (M)this;
	}

	/**
	 * 建立日期 yyyy-MM-dd
	 */
	public String getCreateDate() {
		return getStr("createDate");
	}

	/**
	 * 建立时间 HH:mm:ss
	 */
	public M setCreateTime(String createTime) {
		set("createTime", createTime);
		return (M)this;
	}

	/**
	 * 建立时间 HH:mm:ss
	 */
	public String getCreateTime() {
		return getStr("createTime");
	}

	/**
	 * 省
	 */
	public M setProvince(String province) {
		set("province", province);
		return (M)this;
	}

	/**
	 * 省
	 */
	public String getProvince() {
		return getStr("province");
	}

	/**
	 * 市
	 */
	public M setCity(String city) {
		set("city", city);
		return (M)this;
	}

	/**
	 * 市
	 */
	public String getCity() {
		return getStr("city");
	}

	/**
	 * 县
	 */
	public M setArea(String area) {
		set("area", area);
		return (M)this;
	}

	/**
	 * 县
	 */
	public String getArea() {
		return getStr("area");
	}

	/**
	 * 地址
	 */
	public M setAddr(String addr) {
		set("addr", addr);
		return (M)this;
	}

	/**
	 * 地址
	 */
	public String getAddr() {
		return getStr("addr");
	}

	/**
	 * 是否实名 F:未实名 T：实名;N:审核中
	 */
	public M setIsAuth(String isAuth) {
		set("isAuth", isAuth);
		return (M)this;
	}

	/**
	 * 是否实名 F:未实名 T：实名;N:审核中
	 */
	public String getIsAuth() {
		return getStr("isAuth");
	}

	/**
	 * 实名日期 yyyy-MM-dd
	 */
	public M setAuthDate(String authDate) {
		set("authDate", authDate);
		return (M)this;
	}

	/**
	 * 实名日期 yyyy-MM-dd
	 */
	public String getAuthDate() {
		return getStr("authDate");
	}

	/**
	 * 实名时间 HH:mm:ss
	 */
	public M setAuthTime(String authTime) {
		set("authTime", authTime);
		return (M)this;
	}

	/**
	 * 实名时间 HH:mm:ss
	 */
	public String getAuthTime() {
		return getStr("authTime");
	}

	/**
	 * 证件正面照
	 */
	public M setIdFrontImgUrl(String idFrontImgUrl) {
		set("idFrontImgUrl", idFrontImgUrl);
		return (M)this;
	}

	/**
	 * 证件正面照
	 */
	public String getIdFrontImgUrl() {
		return getStr("idFrontImgUrl");
	}

	/**
	 * 证件反面照
	 */
	public M setIdOppositeImgUrl(String idOppositeImgUrl) {
		set("idOppositeImgUrl", idOppositeImgUrl);
		return (M)this;
	}

	/**
	 * 证件反面照
	 */
	public String getIdOppositeImgUrl() {
		return getStr("idOppositeImgUrl");
	}

	/**
	 * 手持证件照
	 */
	public M setIdHandleImgUrl(String idHandleImgUrl) {
		set("idHandleImgUrl", idHandleImgUrl);
		return (M)this;
	}

	/**
	 * 手持证件照
	 */
	public String getIdHandleImgUrl() {
		return getStr("idHandleImgUrl");
	}

	/**
	 * 银行卡正面照
	 */
	public M setBankCardImgUrl(String bankCardImgUrl) {
		set("bankCardImgUrl", bankCardImgUrl);
		return (M)this;
	}

	/**
	 * 银行卡正面照
	 */
	public String getBankCardImgUrl() {
		return getStr("bankCardImgUrl");
	}

	/**
	 * 头像照片位置
	 */
	public M setHeadImgUrl(String headImgUrl) {
		set("headImgUrl", headImgUrl);
		return (M)this;
	}

	/**
	 * 头像照片位置
	 */
	public String getHeadImgUrl() {
		return getStr("headImgUrl");
	}

	/**
	 * token
	 */
	public M setToken(String token) {
		set("token", token);
		return (M)this;
	}

	/**
	 * token
	 */
	public String getToken() {
		return getStr("token");
	}

	/**
	 * 是否设置支付密码 T：设置 F：未设置
	 */
	public M setIsSetTransPwd(String isSetTransPwd) {
		set("isSetTransPwd", isSetTransPwd);
		return (M)this;
	}

	/**
	 * 是否设置支付密码 T：设置 F：未设置
	 */
	public String getIsSetTransPwd() {
		return getStr("isSetTransPwd");
	}

	/**
	 * 二维码存放地址
	 */
	public M setQrcodeUrl(String qrcodeUrl) {
		set("qrcodeUrl", qrcodeUrl);
		return (M)this;
	}

	/**
	 * 二维码存放地址
	 */
	public String getQrcodeUrl() {
		return getStr("qrcodeUrl");
	}

	/**
	 * 公司id
	 */
	public M setCompanyId(Long companyId) {
		set("companyId", companyId);
		return (M)this;
	}

	/**
	 * 公司id
	 */
	public Long getCompanyId() {
		return getLong("companyId");
	}

	/**
	 * staff:普通员工,manage:管理员,front:前台
	 */
	public M setRole(String role) {
		set("role", role);
		return (M)this;
	}

	/**
	 * staff:普通员工,manage:管理员,front:前台
	 */
	public String getRole() {
		return getStr("role");
	}

	/**
	 * 密钥 用于加解密身份证号、卡号
	 */
	public M setWorkKey(String workKey) {
		set("workKey", workKey);
		return (M)this;
	}

	/**
	 * 密钥 用于加解密身份证号、卡号
	 */
	public String getWorkKey() {
		return getStr("workKey");
	}

	/**
	 * 审核失败原因
	 */
	public M setFailReason(String failReason) {
		set("failReason", failReason);
		return (M)this;
	}

	/**
	 * 审核失败原因
	 */
	public String getFailReason() {
		return getStr("failReason");
	}

	/**
	 * 用户唯一标识码
	 */
	public M setSoleCode(String soleCode) {
		set("soleCode", soleCode);
		return (M)this;
	}

	/**
	 * 用户唯一标识码
	 */
	public String getSoleCode() {
		return getStr("soleCode");
	}

	/**
	 * 有效期
	 */
	public M setValidityDate(String validityDate) {
		set("validityDate", validityDate);
		return (M)this;
	}

	/**
	 * 有效期
	 */
	public String getValidityDate() {
		return getStr("validityDate");
	}

	/**
	 * 性别
	 */
	public M setSex(String sex) {
		set("sex", sex);
		return (M)this;
	}

	/**
	 * 性别
	 */
	public String getSex() {
		return getStr("sex");
	}

	/**
	 * 友盟设备号
	 */
	public M setDeviceToken(String deviceToken) {
		set("deviceToken", deviceToken);
		return (M)this;
	}

	/**
	 * 友盟设备号
	 */
	public String getDeviceToken() {
		return getStr("deviceToken");
	}

	/**
	 * 1--ios 2--andriod
	 */
	public M setDeviceType(String deviceType) {
		set("deviceType", deviceType);
		return (M)this;
	}

	/**
	 * 1--ios 2--andriod
	 */
	public String getDeviceType() {
		return getStr("deviceType");
	}

	/**
	 * T---在线  F--离线
	 */
	public M setIsOnlineApp(String isOnlineApp) {
		set("isOnlineApp", isOnlineApp);
		return (M)this;
	}

	/**
	 * T---在线  F--离线
	 */
	public String getIsOnlineApp() {
		return getStr("isOnlineApp");
	}

	/**
	 * 微信openid，关注公众号并使用公众号登入后产生

	 */
	public M setWxOpenId(String wxOpenId) {
		set("wx_open_id", wxOpenId);
		return (M)this;
	}

	/**
	 * 微信openid，关注公众号并使用公众号登入后产生

	 */
	public String getWxOpenId() {
		return getStr("wx_open_id");
	}

	/**
	 * 扩展字段1
	 */
	public M setExp1(String exp1) {
		set("exp1", exp1);
		return (M)this;
	}

	/**
	 * 扩展字段1
	 */
	public String getExp1() {
		return getStr("exp1");
	}

	/**
	 * 扩展字段2
	 */
	public M setExp2(String exp2) {
		set("exp2", exp2);
		return (M)this;
	}

	/**
	 * 扩展字段2
	 */
	public String getExp2() {
		return getStr("exp2");
	}

}
