package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseActHiIdentitylink<M extends BaseActHiIdentitylink<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("ID_", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("ID_");
	}

	public M setGroupId(java.lang.String groupId) {
		set("GROUP_ID_", groupId);
		return (M)this;
	}
	
	public java.lang.String getGroupId() {
		return getStr("GROUP_ID_");
	}

	public M setType(java.lang.String type) {
		set("TYPE_", type);
		return (M)this;
	}
	
	public java.lang.String getType() {
		return getStr("TYPE_");
	}

	public M setUserId(java.lang.String userId) {
		set("USER_ID_", userId);
		return (M)this;
	}
	
	public java.lang.String getUserId() {
		return getStr("USER_ID_");
	}

	public M setTaskId(java.lang.String taskId) {
		set("TASK_ID_", taskId);
		return (M)this;
	}
	
	public java.lang.String getTaskId() {
		return getStr("TASK_ID_");
	}

	public M setProcInstId(java.lang.String procInstId) {
		set("PROC_INST_ID_", procInstId);
		return (M)this;
	}
	
	public java.lang.String getProcInstId() {
		return getStr("PROC_INST_ID_");
	}

}
