package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseVCar<M extends BaseVCar<M>> extends Model<M> implements IBean {

	/**
	 * ????ͨ??ID
	 */
	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * ????ͨ??ID
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * ???ƺ
	 */
	public M setPlate(java.lang.String plate) {
		set("plate", plate);
		return (M)this;
	}
	
	/**
	 * ???ƺ
	 */
	public java.lang.String getPlate() {
		return getStr("plate");
	}

	/**
	 * ???????
	 */
	public M setVisitDate(java.lang.String visitDate) {
		set("visitDate", visitDate);
		return (M)this;
	}
	
	/**
	 * ???????
	 */
	public java.lang.String getVisitDate() {
		return getStr("visitDate");
	}

	/**
	 * ????ʱ?
	 */
	public M setVisitTime(java.lang.String visitTime) {
		set("visitTime", visitTime);
		return (M)this;
	}
	
	/**
	 * ????ʱ?
	 */
	public java.lang.String getVisitTime() {
		return getStr("visitTime");
	}

	/**
	 * ???ʼ?¼ID
	 */
	public M setVisitId(java.lang.Long visitId) {
		set("visitId", visitId);
		return (M)this;
	}
	
	/**
	 * ???ʼ?¼ID
	 */
	public java.lang.Long getVisitId() {
		return getLong("visitId");
	}

	/**
	 * ״̬ applyConfirm:?????У?applySuccess:???ܷ??ʣ?applyFail:?ܾ????
	 */
	public M setCStatus(java.lang.String cStatus) {
		set("cStatus", cStatus);
		return (M)this;
	}
	
	/**
	 * ״̬ applyConfirm:?????У?applySuccess:???ܷ??ʣ?applyFail:?ܾ????
	 */
	public java.lang.String getCStatus() {
		return getStr("cStatus");
	}

	/**
	 * ??????ID
	 */
	public M setApprovalUserId(java.lang.Long approvalUserId) {
		set("approvalUserId", approvalUserId);
		return (M)this;
	}
	
	/**
	 * ??????ID
	 */
	public java.lang.Long getApprovalUserId() {
		return getLong("approvalUserId");
	}

	public M setApprovalDateTime(java.lang.String approvalDateTime) {
		set("approvalDateTime", approvalDateTime);
		return (M)this;
	}
	
	public java.lang.String getApprovalDateTime() {
		return getStr("approvalDateTime");
	}

	/**
	 * 访问者手机号码
	 */
	public M setPhone(java.lang.String phone) {
		set("phone", phone);
		return (M)this;
	}
	
	/**
	 * 访问者手机号码
	 */
	public java.lang.String getPhone() {
		return getStr("phone");
	}

	/**
	 * 访问者姓名
	 */
	public M setUserName(java.lang.String userName) {
		set("userName", userName);
		return (M)this;
	}
	
	/**
	 * 访问者姓名
	 */
	public java.lang.String getUserName() {
		return getStr("userName");
	}

	/**
	 * 出入口
	 */
	public M setGate(java.lang.String gate) {
		set("gate", gate);
		return (M)this;
	}
	
	/**
	 * 出入口
	 */
	public java.lang.String getGate() {
		return getStr("gate");
	}

	/**
	 * 受访人ID
	 */
	public M setIntervieweeId(java.lang.Long intervieweeId) {
		set("intervieweeId", intervieweeId);
		return (M)this;
	}
	
	/**
	 * 受访人ID
	 */
	public java.lang.Long getIntervieweeId() {
		return getLong("intervieweeId");
	}

	/**
	 * 事由
	 */
	public M setReason(java.lang.String reason) {
		set("reason", reason);
		return (M)this;
	}
	
	/**
	 * 事由
	 */
	public java.lang.String getReason() {
		return getStr("reason");
	}

}
