package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseVNotice<M extends BaseVNotice<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 标题
	 */
	public M setNoticeTitle(java.lang.String noticeTitle) {
		set("noticeTitle", noticeTitle);
		return (M)this;
	}
	
	/**
	 * 标题
	 */
	public java.lang.String getNoticeTitle() {
		return getStr("noticeTitle");
	}

	/**
	 * 内容
	 */
	public M setContent(java.lang.String content) {
		set("content", content);
		return (M)this;
	}
	
	/**
	 * 内容
	 */
	public java.lang.String getContent() {
		return getStr("content");
	}

	/**
	 * 建立日期 yyyy-MM-dd
	 */
	public M setCreateDate(java.lang.String createDate) {
		set("createDate", createDate);
		return (M)this;
	}
	
	/**
	 * 建立日期 yyyy-MM-dd
	 */
	public java.lang.String getCreateDate() {
		return getStr("createDate");
	}

	/**
	 * 建立时间 HH:mm:ss
	 */
	public M setCreateTime(java.lang.String createTime) {
		set("createTime", createTime);
		return (M)this;
	}
	
	/**
	 * 建立时间 HH:mm:ss
	 */
	public java.lang.String getCreateTime() {
		return getStr("createTime");
	}

	/**
	 * 状态 normal:正常 disable:失效
	 */
	public M setCstatus(java.lang.String cstatus) {
		set("cstatus", cstatus);
		return (M)this;
	}
	
	/**
	 * 状态 normal:正常 disable:失效
	 */
	public java.lang.String getCstatus() {
		return getStr("cstatus");
	}

	public M setUpdateTime(java.lang.String updateTime) {
		set("updateTime", updateTime);
		return (M)this;
	}
	
	public java.lang.String getUpdateTime() {
		return getStr("updateTime");
	}

}
