package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbFailreceive<M extends BaseTbFailreceive<M>> extends Model<M> implements IBean {

	public M setFailedId(java.lang.Integer failedId) {
		set("failedId", failedId);
		return (M)this;
	}
	
	public java.lang.Integer getFailedId() {
		return getInt("failedId");
	}

	/**
	 * 设备IP地址（人脸设备）（主键1）
	 */
	public M setFaceIp(java.lang.String faceIp) {
		set("faceIp", faceIp);
		return (M)this;
	}
	
	/**
	 * 设备IP地址（人脸设备）（主键1）
	 */
	public java.lang.String getFaceIp() {
		return getStr("faceIp");
	}

	/**
	 * 用户姓名
	 */
	public M setUserName(java.lang.String userName) {
		set("userName", userName);
		return (M)this;
	}
	
	/**
	 * 用户姓名
	 */
	public java.lang.String getUserName() {
		return getStr("userName");
	}

	/**
	 * 用户证件号（主键2）
	 */
	public M setIdCard(java.lang.String idCard) {
		set("idCard", idCard);
		return (M)this;
	}
	
	/**
	 * 用户证件号（主键2）
	 */
	public java.lang.String getIdCard() {
		return getStr("idCard");
	}

	/**
	 * 人员类型（员工-staff，访客-visitor,发起共享-applicat）（主键3）
	 */
	public M setUserType(java.lang.String userType) {
		set("userType", userType);
		return (M)this;
	}
	
	/**
	 * 人员类型（员工-staff，访客-visitor,发起共享-applicat）（主键3）
	 */
	public java.lang.String getUserType() {
		return getStr("userType");
	}

	/**
	 * 下发失败接收时间
	 */
	public M setReceiveTime(java.lang.String receiveTime) {
		set("receiveTime", receiveTime);
		return (M)this;
	}
	
	/**
	 * 下发失败接收时间
	 */
	public java.lang.String getReceiveTime() {
		return getStr("receiveTime");
	}

	/**
	 * 下发接收标识（0-成功，1-失败）
	 */
	public M setReceiveFlag(java.lang.String receiveFlag) {
		set("receiveFlag", receiveFlag);
		return (M)this;
	}
	
	/**
	 * 下发接收标识（0-成功，1-失败）
	 */
	public java.lang.String getReceiveFlag() {
		return getStr("receiveFlag");
	}

	/**
	 * 访客记录表主键（visitor类型才有）
	 */
	public M setVisitorUUID(java.lang.String visitorUUID) {
		set("visitorUUID", visitorUUID);
		return (M)this;
	}
	
	/**
	 * 访客记录表主键（visitor类型才有）
	 */
	public java.lang.String getVisitorUUID() {
		return getStr("visitorUUID");
	}

	/**
	 * 失败操作（save-下发，delete-删除）（主键4）
	 */
	public M setOpera(java.lang.String opera) {
		set("opera", opera);
		return (M)this;
	}
	
	/**
	 * 失败操作（save-下发，delete-删除）（主键4）
	 */
	public java.lang.String getOpera() {
		return getStr("opera");
	}

	/**
	 * 下发次数（超过5次不再下发）
	 */
	public M setDownNum(java.lang.Integer downNum) {
		set("downNum", downNum);
		return (M)this;
	}
	
	/**
	 * 下发次数（超过5次不再下发）
	 */
	public java.lang.Integer getDownNum() {
		return getInt("downNum");
	}

	/**
	 * 错误码
	 */
	public M setErrorCode(java.lang.Integer errorCode) {
		set("errorCode", errorCode);
		return (M)this;
	}
	
	/**
	 * 错误码
	 */
	public java.lang.Integer getErrorCode() {
		return getInt("errorCode");
	}

	/**
	 * 错误原因
	 */
	public M setErrorMsg(java.lang.String errorMsg) {
		set("errorMsg", errorMsg);
		return (M)this;
	}
	
	/**
	 * 错误原因
	 */
	public java.lang.String getErrorMsg() {
		return getStr("errorMsg");
	}

}
