package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseVAppCheckintime<M extends BaseVAppCheckintime<M>> extends Model<M> implements IBean {

	/**
	 * 考勤打卡
	 */
	public M setId(Long id) {
		set("id", id);
		return (M)this;
	}

	/**
	 * 考勤打卡
	 */
	public Long getId() {
		return getLong("id");
	}

	/**
	 * 上班时间，表示为距离当天0点的秒数。
	 */
	public M setWorkSec(Integer workSec) {
		set("work_sec", workSec);
		return (M)this;
	}

	/**
	 * 上班时间，表示为距离当天0点的秒数。
	 */
	public Integer getWorkSec() {
		return getInt("work_sec");
	}

	/**
	 * 下班时间，表示为距离当天0点的秒数。
	 */
	public M setOffWorkSec(Integer offWorkSec) {
		set("off_work_sec", offWorkSec);
		return (M)this;
	}

	/**
	 * 下班时间，表示为距离当天0点的秒数。
	 */
	public Integer getOffWorkSec() {
		return getInt("off_work_sec");
	}

	/**
	 * 上班提醒时间，表示为距离当天0点的秒数。
	 */
	public M setRemindWorkSec(Integer remindWorkSec) {
		set("remind_work_sec", remindWorkSec);
		return (M)this;
	}

	/**
	 * 上班提醒时间，表示为距离当天0点的秒数。
	 */
	public Integer getRemindWorkSec() {
		return getInt("remind_work_sec");
	}

	/**
	 * 下班提醒时间，表示为距离当天0点的秒数。
	 */
	public M setRemindOffWorkSec(Integer remindOffWorkSec) {
		set("remind_off_work_sec", remindOffWorkSec);
		return (M)this;
	}

	/**
	 * 下班提醒时间，表示为距离当天0点的秒数。
	 */
	public Integer getRemindOffWorkSec() {
		return getInt("remind_off_work_sec");
	}

}
