package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseVCar<M extends BaseVCar<M>> extends Model<M> implements IBean {

	/**
	 * ????ͨ??ID
	 */
	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * ????ͨ??ID
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * ???ƺ
	 */
	public M setPlate(java.lang.String plate) {
		set("plate", plate);
		return (M)this;
	}
	
	/**
	 * ???ƺ
	 */
	public java.lang.String getPlate() {
		return getStr("plate");
	}

	/**
	 * ???????
	 */
	public M setVisitDate(java.lang.String visitDate) {
		set("visitDate", visitDate);
		return (M)this;
	}
	
	/**
	 * ???????
	 */
	public java.lang.String getVisitDate() {
		return getStr("visitDate");
	}

	/**
	 * ????ʱ?
	 */
	public M setVisitTime(java.lang.String visitTime) {
		set("visitTime", visitTime);
		return (M)this;
	}
	
	/**
	 * ????ʱ?
	 */
	public java.lang.String getVisitTime() {
		return getStr("visitTime");
	}

	/**
	 * ???ʼ?¼ID
	 */
	public M setVisitId(java.lang.Long visitId) {
		set("visitId", visitId);
		return (M)this;
	}
	
	/**
	 * ???ʼ?¼ID
	 */
	public java.lang.Long getVisitId() {
		return getLong("visitId");
	}

	/**
	 * ״̬ applyConfirm:?????У?applySuccess:???ܷ??ʣ?applyFail:?ܾ????
	 */
	public M setCStatus(java.lang.String cStatus) {
		set("cStatus", cStatus);
		return (M)this;
	}
	
	/**
	 * ״̬ applyConfirm:?????У?applySuccess:???ܷ??ʣ?applyFail:?ܾ????
	 */
	public java.lang.String getCStatus() {
		return getStr("cStatus");
	}

	/**
	 * ??????ID
	 */
	public M setApprovalUserId(java.lang.Long approvalUserId) {
		set("approvalUserId", approvalUserId);
		return (M)this;
	}
	
	/**
	 * ??????ID
	 */
	public java.lang.Long getApprovalUserId() {
		return getLong("approvalUserId");
	}

	public M setApprovalDateTime(java.lang.String approvalDateTime) {
		set("approvalDateTime", approvalDateTime);
		return (M)this;
	}
	
	public java.lang.String getApprovalDateTime() {
		return getStr("approvalDateTime");
	}

	/**
	 * 访问者手机号码
	 */
	public M setPhone(java.lang.String phone) {
		set("phone", phone);
		return (M)this;
	}
	
	/**
	 * 访问者手机号码
	 */
	public java.lang.String getPhone() {
		return getStr("phone");
	}

	/**
	 * 访问者姓名
	 */
	public M setUserName(java.lang.String userName) {
		set("userName", userName);
		return (M)this;
	}
	
	/**
	 * 访问者姓名
	 */
	public java.lang.String getUserName() {
		return getStr("userName");
	}

	/**
	 * 出入口
	 */
	public M setGate(java.lang.String gate) {
		set("gate", gate);
		return (M)this;
	}
	
	/**
	 * 出入口
	 */
	public java.lang.String getGate() {
		return getStr("gate");
	}

	/**
	 * 受访人ID
	 */
	public M setIntervieweeId(java.lang.Long intervieweeId) {
		set("intervieweeId", intervieweeId);
		return (M)this;
	}
	
	/**
	 * 受访人ID
	 */
	public java.lang.Long getIntervieweeId() {
		return getLong("intervieweeId");
	}

	/**
	 * 事由
	 */
	public M setReason(java.lang.String reason) {
		set("reason", reason);
		return (M)this;
	}
	
	/**
	 * 事由
	 */
	public java.lang.String getReason() {
		return getStr("reason");
	}

	/**
	 * 受访者姓名
	 */
	public M setVisitorName(java.lang.String visitorName) {
		set("visitorName", visitorName);
		return (M)this;
	}
	
	/**
	 * 受访者姓名
	 */
	public java.lang.String getVisitorName() {
		return getStr("visitorName");
	}

	/**
	 * 受访者手机号
	 */
	public M setVisitorPhone(java.lang.String visitorPhone) {
		set("visitorPhone", visitorPhone);
		return (M)this;
	}
	
	/**
	 * 受访者手机号
	 */
	public java.lang.String getVisitorPhone() {
		return getStr("visitorPhone");
	}

	/**
	 * 出入类型
	 */
	public M setInOutType(java.lang.Integer inOutType) {
		set("inOutType", inOutType);
		return (M)this;
	}
	
	/**
	 * 出入类型
	 */
	public java.lang.Integer getInOutType() {
		return getInt("inOutType");
	}

	/**
	 * 受访者单位
	 */
	public M setVisitorDept(java.lang.String visitorDept) {
		set("visitorDept", visitorDept);
		return (M)this;
	}
	
	/**
	 * 受访者单位
	 */
	public java.lang.String getVisitorDept() {
		return getStr("visitorDept");
	}

	/**
	 * 随车人数
	 */
	public M setNum(java.lang.Integer num) {
		set("num", num);
		return (M)this;
	}
	
	/**
	 * 随车人数
	 */
	public java.lang.Integer getNum() {
		return getInt("num");
	}

	/**
	 * 审批流程ID
	 */
	public M setProcessId(java.lang.String processId) {
		set("processId", processId);
		return (M)this;
	}
	
	/**
	 * 审批流程ID
	 */
	public java.lang.String getProcessId() {
		return getStr("processId");
	}

	/**
	 * 开始日期
	 */
	public M setStartDate(java.lang.String startDate) {
		set("startDate", startDate);
		return (M)this;
	}
	
	/**
	 * 开始日期
	 */
	public java.lang.String getStartDate() {
		return getStr("startDate");
	}

	/**
	 * 结束日期
	 */
	public M setEndDate(java.lang.String endDate) {
		set("endDate", endDate);
		return (M)this;
	}
	
	/**
	 * 结束日期
	 */
	public java.lang.String getEndDate() {
		return getStr("endDate");
	}

}
