package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseVAdBanner<M extends BaseVAdBanner<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 广告标题
	 */
	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M)this;
	}
	
	/**
	 * 广告标题
	 */
	public java.lang.String getTitle() {
		return getStr("title");
	}

	/**
	 * 广告图片路径
	 */
	public M setImgUrl(java.lang.String imgUrl) {
		set("imgUrl", imgUrl);
		return (M)this;
	}
	
	/**
	 * 广告图片路径
	 */
	public java.lang.String getImgUrl() {
		return getStr("imgUrl");
	}

	/**
	 * 超链接
	 */
	public M setHrefUrl(java.lang.String hrefUrl) {
		set("hrefUrl", hrefUrl);
		return (M)this;
	}
	
	/**
	 * 超链接
	 */
	public java.lang.String getHrefUrl() {
		return getStr("hrefUrl");
	}

	/**
	 * 广告状态 0无效 1有效
	 */
	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}
	
	/**
	 * 广告状态 0无效 1有效
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	/**
	 * 生产时间
	 */
	public M setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
		return (M)this;
	}
	
	/**
	 * 生产时间
	 */
	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	/**
	 * 修改时间
	 */
	public M setUpdateTime(java.lang.String updateTime) {
		set("updateTime", updateTime);
		return (M)this;
	}
	
	/**
	 * 修改时间
	 */
	public java.lang.String getUpdateTime() {
		return getStr("updateTime");
	}

	/**
	 * 排序，数值越高，越靠前
	 */
	public M setOrders(java.lang.Integer orders) {
		set("orders", orders);
		return (M)this;
	}
	
	/**
	 * 排序，数值越高，越靠前
	 */
	public java.lang.Integer getOrders() {
		return getInt("orders");
	}

}
