package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseVCompVipUser<M extends BaseVCompVipUser<M>> extends Model<M> implements IBean {

	/**
	 * VIP管理
	 */
	public M setId(Long id) {
		set("id", id);
		return (M)this;
	}

	/**
	 * VIP管理
	 */
	public Long getId() {
		return getLong("id");
	}

	/**
	 * 大楼id
	 */
	public M setOrgId(Long orgId) {
		set("orgId", orgId);
		return (M)this;
	}

	/**
	 * 大楼id
	 */
	public Long getOrgId() {
		return getLong("orgId");
	}

	/**
	 * 更新时间HH:mm:ss hh"ii:ss
	 */
	public M setUpdateTime(String updateTime) {
		set("updateTime", updateTime);
		return (M)this;
	}

	/**
	 * 更新时间HH:mm:ss hh"ii:ss
	 */
	public String getUpdateTime() {
		return getStr("updateTime");
	}

	/**
	 * 用户Id
	 */
	public M setUserId(Long userId) {
		set("userId", userId);
		return (M)this;
	}

	/**
	 * 用户Id
	 */
	public Long getUserId() {
		return getLong("userId");
	}

	/**
	 * 请求id
	 */
	public M setPostId(Long postId) {
		set("postId", postId);
		return (M)this;
	}

	/**
	 * 请求id
	 */
	public Long getPostId() {
		return getLong("postId");
	}

	/**
	 * 用户姓名
	 */
	public M setUserName(String userName) {
		set("userName", userName);
		return (M)this;
	}

	/**
	 * 用户姓名
	 */
	public String getUserName() {
		return getStr("userName");
	}

	/**
	 * 创建日期yy:MM:dd
	 */
	public M setCreateDate(String createDate) {
		set("createDate", createDate);
		return (M)this;
	}

	/**
	 * 创建日期yy:MM:dd
	 */
	public String getCreateDate() {
		return getStr("createDate");
	}

	/**
	 * 创建时间HH:mm:ss
	 */
	public M setCreateTime(String createTime) {
		set("createTime", createTime);
		return (M)this;
	}

	/**
	 * 创建时间HH:mm:ss
	 */
	public String getCreateTime() {
		return getStr("createTime");
	}

	/**
	 * 角色:(staff:普通员工,manage:管理员,front:前台)
	 */
	public M setRoleType(String roleType) {
		set("roleType", roleType);
		return (M)this;
	}

	/**
	 * 角色:(staff:普通员工,manage:管理员,front:前台)
	 */
	public String getRoleType() {
		return getStr("roleType");
	}

	/**
	 * 状态：确认:applySuc/未确认:applying/确认不通过:applyFail
	 */
	public M setStatus(String status) {
		set("status", status);
		return (M)this;
	}

	/**
	 * 状态：确认:applySuc/未确认:applying/确认不通过:applyFail
	 */
	public String getStatus() {
		return getStr("status");
	}

	/**
	 * normal为正常，deleted为删除
	 */
	public M setCurrentStatus(String currentStatus) {
		set("currentStatus", currentStatus);
		return (M)this;
	}

	/**
	 * normal为正常，deleted为删除
	 */
	public String getCurrentStatus() {
		return getStr("currentStatus");
	}

}
