package com.xiaosong.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseWkRecord<M extends BaseWkRecord<M>> extends Model<M> implements IBean {

	/**
	 * 打卡记录id
	 */
	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 打卡记录id
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 用户id
	 */
	public M setUserId(java.lang.Long userId) {
		set("user_id", userId);
		return (M)this;
	}
	
	/**
	 * 用户id
	 */
	public java.lang.Long getUserId() {
		return getLong("user_id");
	}

	/**
	 * 公司id
	 */
	public M setCompanyId(java.lang.Long companyId) {
		set("company_id", companyId);
		return (M)this;
	}
	
	/**
	 * 公司id
	 */
	public java.lang.Long getCompanyId() {
		return getLong("company_id");
	}

	/**
	 * 1上班打卡，2下班打卡，3外出打卡
	 */
	public M setCheckinType(java.lang.String checkinType) {
		set("checkin_type", checkinType);
		return (M)this;
	}
	
	/**
	 * 1上班打卡，2下班打卡，3外出打卡
	 */
	public java.lang.String getCheckinType() {
		return getStr("checkin_type");
	}

	/**
	 * 异常类型，字符串，包括：1 时间异常，2 地点异常，未打卡，3 wifi异常，4 非常用设备。如果有多个异常，以分号间隔
	 */
	public M setExceptionType(java.lang.String exceptionType) {
		set("exception_type", exceptionType);
		return (M)this;
	}
	
	/**
	 * 异常类型，字符串，包括：1 时间异常，2 地点异常，未打卡，3 wifi异常，4 非常用设备。如果有多个异常，以分号间隔
	 */
	public java.lang.String getExceptionType() {
		return getStr("exception_type");
	}

	/**
	 * 打卡时间
	 */
	public M setCheckinDate(java.lang.String checkinDate) {
		set("checkin_date", checkinDate);
		return (M)this;
	}
	
	/**
	 * 打卡时间
	 */
	public java.lang.String getCheckinDate() {
		return getStr("checkin_date");
	}

	/**
	 * 打卡时间
	 */
	public M setCheckinTime(java.lang.String checkinTime) {
		set("checkin_time", checkinTime);
		return (M)this;
	}
	
	/**
	 * 打卡时间
	 */
	public java.lang.String getCheckinTime() {
		return getStr("checkin_time");
	}

	/**
	 * 打卡地点title
	 */
	public M setLocationTitle(java.lang.String locationTitle) {
		set("location_title", locationTitle);
		return (M)this;
	}
	
	/**
	 * 打卡地点title
	 */
	public java.lang.String getLocationTitle() {
		return getStr("location_title");
	}

	/**
	 * 打卡地点详情
	 */
	public M setLocationDetail(java.lang.String locationDetail) {
		set("location_detail", locationDetail);
		return (M)this;
	}
	
	/**
	 * 打卡地点详情
	 */
	public java.lang.String getLocationDetail() {
		return getStr("location_detail");
	}

	/**
	 * 打卡wifi名称
	 */
	public M setWifiName(java.lang.String wifiName) {
		set("wifi_name", wifiName);
		return (M)this;
	}
	
	/**
	 * 打卡wifi名称
	 */
	public java.lang.String getWifiName() {
		return getStr("wifi_name");
	}

	/**
	 * 打卡的MAC地址/bssid
	 */
	public M setWifiMac(java.lang.String wifiMac) {
		set("wifi_mac", wifiMac);
		return (M)this;
	}
	
	/**
	 * 打卡的MAC地址/bssid
	 */
	public java.lang.String getWifiMac() {
		return getStr("wifi_mac");
	}

	/**
	 * 打卡设备
	 */
	public M setCheckinDivice(java.lang.String checkinDivice) {
		set("checkin_divice", checkinDivice);
		return (M)this;
	}
	
	/**
	 * 打卡设备
	 */
	public java.lang.String getCheckinDivice() {
		return getStr("checkin_divice");
	}

	/**
	 * 打卡备注 文字或照片地址
	 */
	public M setNotes(java.lang.String notes) {
		set("notes", notes);
		return (M)this;
	}
	
	/**
	 * 打卡备注 文字或照片地址
	 */
	public java.lang.String getNotes() {
		return getStr("notes");
	}

	/**
	 * 打卡的附件media_id，可使用media/get获取附件
	 */
	public M setMediaids(java.lang.String mediaids) {
		set("mediaids", mediaids);
		return (M)this;
	}
	
	/**
	 * 打卡的附件media_id，可使用media/get获取附件
	 */
	public java.lang.String getMediaids() {
		return getStr("mediaids");
	}

	/**
	 * 位置打卡地点纬度，是实际纬度的1000000倍，与腾讯地图一致采用GCJ-02坐标系统标准
	 */
	public M setLat(java.lang.Long lat) {
		set("lat", lat);
		return (M)this;
	}
	
	/**
	 * 位置打卡地点纬度，是实际纬度的1000000倍，与腾讯地图一致采用GCJ-02坐标系统标准
	 */
	public java.lang.Long getLat() {
		return getLong("lat");
	}

	/**
	 * 位置打卡地点经度，是实际经度的1000000倍，与腾讯地图一致采用GCJ-02坐标系统标准
	 */
	public M setLng(java.lang.Long lng) {
		set("lng", lng);
		return (M)this;
	}
	
	/**
	 * 位置打卡地点经度，是实际经度的1000000倍，与腾讯地图一致采用GCJ-02坐标系统标准
	 */
	public java.lang.Long getLng() {
		return getLong("lng");
	}

	/**
	 * 'T' 有效 'F' 失效
	 */
	public M setEffective(java.lang.String effective) {
		set("effective", effective);
		return (M)this;
	}
	
	/**
	 * 'T' 有效 'F' 失效
	 */
	public java.lang.String getEffective() {
		return getStr("effective");
	}

	/**
	 * 创建时间
	 */
	public M setCreatTime(java.util.Date creatTime) {
		set("creat_time", creatTime);
		return (M)this;
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreatTime() {
		return get("creat_time");
	}

	/**
	 * 更新时间
	 */
	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	/**
	 * 拓展字段
	 */
	public M setExp1(java.lang.String exp1) {
		set("exp1", exp1);
		return (M)this;
	}
	
	/**
	 * 拓展字段
	 */
	public java.lang.String getExp1() {
		return getStr("exp1");
	}

	/**
	 * 拓展字段
	 */
	public M setExp2(java.lang.String exp2) {
		set("exp2", exp2);
		return (M)this;
	}
	
	/**
	 * 拓展字段
	 */
	public java.lang.String getExp2() {
		return getStr("exp2");
	}

	/**
	 * 拓展字段
	 */
	public M setExp3(java.lang.String exp3) {
		set("exp3", exp3);
		return (M)this;
	}
	
	/**
	 * 拓展字段
	 */
	public java.lang.String getExp3() {
		return getStr("exp3");
	}

}
